### ISSUE TITLE
Click node to navigate to different map

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#102]
As maps get more complex it would be good to be able to have an overview map that leads to sub-maps. I appreciate that Liveview does that after a fashion but wondered whether there was any other way this could be done using pre-defined views. Apologies in advance if this is a FAQ.

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

I once added a similar feature to TiddlyMap. It was called "diving mode" (https://github.com/felixhayashi/TW5-TiddlyMap/issues/14#issuecomment-67895980). I removed the feature as it added another level of complexity...

That said, I am waiting till Visjs 4.0 gets released around May where it is possible (in theory) to create sub-groups of nodes.

But maybe your request goes in a different direction? For example in xmind (https://www.xmind.net) you can open separately created mindmaps from a node that exist in another mindmap. Is this what you meant? Then an idea would be to add a rule like the following to tiddlymap:

> If a node exists that has the same name as an existing view, then switch to this view in the editor.

Not sure if this is the best way to handle this. But I agree that it should be possible to link maps.

-Felix

**Comment by Peter-Miller** [comment]
The xmind-style rule sounds good but I guess it would need to be an option to be enabled so as to avoid accidental name clashes?

**Comment by felixhayashi** [comment]
> The xmind-style rule sounds good but I guess it would need to be an option to be enabled so as to avoid accidental name clashes?

yes thought about that too. Maybe, instead of a rule, it would be better to add a field to a tiddler that defines whether and which view should be opened if the tiddler (represented as node in the graph) is clicked.

This field could look like:

`tmap.open-view: Mindmap2`

in this case I do not open the tiddler in the river (?) but instead try to open a view of this name...

Maybe there is also a better way to do this...

**Comment by Peter-Miller** [comment]
The field idea gets my vote. The tiddler should open as well as the view? No urgency with this if you need time to think.

**Comment by felixhayashi** [comment]
> The tiddler should open as well as the view?

Well I don't know what is the best thing to do here. Usually a clicked node a graph will cause the corresponding tiddler to be opened. But in this case, we only want to use the tiddler to "jump" to another view.

> No urgency with this if you need time to think.

Just want to plan this carefully ;)

**Comment by Peter-Miller** [comment]
No harm in using the tiddler to document the gateway to the new view.

**Comment by tobibeer** [comment]
Perhaps it is possible to have vis.js display a "secondary" node that is attached to a node, i.e. a node that is pretty much only "linked" to or rather "next" to the node to which it is of a secondary nature.

What would also be cool was the ability to have a node associated with an arbitrary number of "subgraphs" or "related graphs", so that this "secondary node" no longer opens that other graph when clicked but rather a popup that allows me to select the related graph I am interested in and then move to it.

For this, clearly, a graph or "view" needs a relationship to a node and there needs to be a way to navigate to it, e.g. from the subsystem-graph, to the system-graph or from a variant-graph to the concept-graph, etc...

**Comment by felixhayashi** [comment]
Hi @tobibeer 

> Perhaps it is possible to have vis.js display a "secondary" node that is attached to a node, i.e. a node that is pretty much only "linked" to or rather "next" to the node to which it is of a secondary nature.

Thanks for this suggestion. I get the idea and imagining such a "popup of secondary" nodes would definitely be cool. However, adding "secondary" nodes somewhat breaks the paradigm "each node is a representation of a tiddler" on which the current implementation of tiddlymap relies.

So the next release will feature a solution where I simply reused the current "edit node" dialog that is opened when selecting a node and clicking on "edit node" in the editor toolbar. In this dialog, the user can choose an existing view that is opened when the node is clicked (this will also disable the navigation/opening of a tiddler in the river).

> What would also be cool was the ability to have a node associated with an arbitrary number of "subgraphs" or "related graphs", so that this "secondary node" no longer opens that other graph when clicked but rather a popup that allows me to select the related graph I am interested in and then move to it.

Of course that would be cool ;) but I think this is also possible with the implementation I described above. Simply create an arbitrary number of secondary nodes in the view and link them to views you want to open. Of course these will stay visible all the time…

-Felix

**Comment by tobibeer** [comment]
@felixhayashi, of course, your toolbar approach is both clean and pragmatic :+1: 

> Of course these will stay visible all the time…

I guess that is ok. It's simply a different modeling paradigm, e.g. imagine there is a node that has x subgraphs, then clicking that node could open a view showing those subgraphs and upon clicking any of those subgraph nodes you get to the eventual view that is linked.

So...

* View V => has node N
* after config via toolbar, clicking node N opens graph-view for node N with nodes X, Y and Z
* clicking any of X, Y or Z opens the corresponding graph / view that we wanted to relate to node N
