### ISSUE TITLE
Tiddler configureTiddlyMap doesn't work

### ISSUE THREAD

**Issue by pmario** [felixhayashi/TW5-TiddlyMap#126]
If you open [$:/plugins/felixhayashi/tiddlymap/dialog/configureTiddlyMap](http://felixhayashi.github.io/TW5-TiddlyMap/index.html#%24%3A%2Fplugins%2Ffelixhayashi%2Ftiddlymap%2Fdialog%2FconfigureTiddlyMap) as a standard tiddler, it doesn't work. If this behaviour is intended, imo it should be named "template".

**Comment by felixhayashi** [comment]
Hi @pmario 

yes, this is not intended. This tiddler only makes sense when being invoked as dialog. My naming strategy is that everything below `$:/plugins/felixhayashi/tiddlymap/dialog/` is a dialog template. I think as long as it is not publicly documented to open this tiddler or to change its values, there is no reason to start naming it differently because it is truly plugin internals. Just like users should not start messing with a windows file "configuration_dialog.dll" that resides in a program folder.

Anyhow, if there is an (unwritten?) convention to have the word "template" in the tiddlers name when it cannot be used on its own, I appreciate that you are telling me. I'll name it `$:/plugins/felixhayashi/tiddlymap/templates/dialog/` in the course of the next refactoring cycle.

**Comment by pmario** [comment]
- I did create the issue, because I did an advanced search for "config"
 - I did open the tiddler, and saw, that the debug option was not set, but there is a lot of debug output in the `<f12>` dev window. ... So I thought there must be a problem. .... 
 - Later I found out, that dialog tiddlers are templates. 

hmmm, 
`$:/plugins/felixhayashi/tiddlymap/templates/dialog/` As a developer, I don't like this prefix, since imo it's too long. ... What if you just rename "dialog" to "template" ... Will it destroy your existing naming conventions? ... if yes ... I'd prefer a "wontfix" over an even longer name ;)

**Comment by felixhayashi** [comment]
Hi @pmario 

> $:/plugins/felixhayashi/tiddlymap/templates/dialog/ As a developer, I don't like this prefix, since imo it's too long.

No need to worry about names being too long, I store names as shortcut-properties to have quick access (https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/startup.caretaker.js#L80) ;)

> What if you just rename "dialog" to "template" ... 

that would be too generic because templates do not necessarily need to be dialogs and it will make it harder to keep track of what is a dialog template and what isn't.

> Will it destroy your existing naming conventions?

Yes, at the moment I assemble the dialog names at runtime based on the prefix (https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/lib.dialog_manager.js#L173) and the dialog name. Same for the different dialog buttons (https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/lib.dialog_manager.js#L143). But as said, if it makes sense to add the word template to it, I will do it when I do the next refactoring, in the end, it is just a searchNreplace task anyways...

**Comment by felixhayashi** [comment]
> I'd prefer a "wontfix" over an even longer name ;)

Oh sorry I overread that part. Then maybe it will be a nonfix because I cannot simply replace "dialog" with "template".

**Comment by pmario** [comment]
I'll close it for now, since I can't come up with a better idea / solution. We'll see if someone else stumbles upon it.

**Comment by felixhayashi** [comment]
> We'll see if someone else stumbles upon it. 

Hehe, I think 99% of the users are not as experienced as you are so chances are good that nobody will notice ;)
