### ISSUE TITLE
Dialog button [Quit] is confusing

### ISSUE THREAD

**Issue by pmario** [felixhayashi/TW5-TiddlyMap#127]
Most dialogs seem to have [OK] [Cancel] buttons but the "Edge-type editor" has [Save] [Create] [Quit]

IMO [Quit] does the same as [Cancel] but since it is a different name, it is confusing. Would it be possible to rename it?

![tiddlymap-dialog-buttons](https://cloud.githubusercontent.com/assets/374655/7907378/f2a488fe-0838-11e5-9279-3e0e72d81325.gif)

**Comment by felixhayashi** [comment]
Hi @pmario 

I named this one "quit" and not "cancel" because this dialog is special. It is like a *window* that stays open not just to answer a single question but really like a mini program where you can stay for a while and when you are done after some time, you have to close it. So cancel would be misleading: "am I cancelling everything I changed while being in this editor creating 4 edge types and configuring them?"

**Comment by pmario** [comment]
You are right. I found out, that there is a different behaviour, after I created the issue. ... 
For me Quit is Close without saving. 

What about "Done" ? .... While Done means "Save and close" ... at least for me :)

**Comment by felixhayashi** [comment]
> For me Quit is Close without saving. 

Then "quit" seems reasonable since the last change is not saved unless you pressed the save button :) If you prefer "close" over "quit", I don't mind renaming it... But I would not call it "done" for the same reasons you mentioned (=save and close).

**Comment by pmario** [comment]
hmm, 

may be we can add a tooltip, that tells the user what's going on. So the name of the button is less important.

**Comment by felixhayashi** [comment]
Great idea! I'll add tooltips to all buttons. Didn't think of that at all.
