### ISSUE TITLE
Parent.of child.of types of connections.

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#13]
Letting the connections having a type can allow you to express complex relationships. Is not just about labels, maybe you want a label "property of" but you want to express that the linked node is "child of" the connected node. This can be visually represented by nodes sizes and text weight.

**Comment by felixhayashi** [comment]
I will add the possibility to add different styling to edges (weight, color, style etc.) as announced (#4) but I cannot go beyond that at the moment, unless vis.js allows me. So I close this issue now. If some new information arrives, I will link it to this issue.

**Comment by felixhayashi** [comment]
Seems like vis will allow this in 4.0, I'll leave this issue open as a reminder...

**Comment by xnmp** [comment]
So at the moment is there a field that defines the size of the node? Surely such a thing would be useful regardless of what people will want to use node size to represent.

**Comment by felixhayashi** [comment]
Hi @xnmp 

I had a look at it and unfortunately it seems that vis.js does not support changing the node size at the moment. I ca

Please have a look at: http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Tweaking%20the%20Graph

Maybe you could do the following:

    {
      "nodes.fontSize": "30"
    }

![selection_650](https://cloud.githubusercontent.com/assets/4307137/7754206/0be8873a-ffeb-11e4-8c0b-5e0293603f5c.png)

**Comment by xnmp** [comment]
So suppose I wanted to make node number "837211ea-ed82-4b1c-9847-b64fab9ae78e" really big. I tried the below, but it obviously didn't work. How do I amend it?

<pre><code>
{
"groups": {
  "mygroup": {
    "fontSize": "30"
  }
}
};
  

{
  "nodes":{
	{"id": "837211ea-ed82-4b1c-9847-b64fab9ae78e", group: 'mygroup'}
}
};
</code></pre>

**Comment by felixhayashi** [comment]
Hi @xnmp 

nope, this is not how you do it. It is not possible at the moment to manually assign groups or styles to individual nodes or groups of nodes.

There is an open ticket for that: https://github.com/felixhayashi/TW5-TiddlyMap/issues/16. So its on my agenda but I cannot say when it gets implemented. Because I also want to wait till visjs 4.0 is released where this might be possible out of the box...

-Felix

**Comment by xnmp** [comment]
Good news, it's just been released!

http://visjs.org/blog.html

**Comment by felixhayashi** [comment]
yap :) because they changed much of the API I'll need some time before we can use it for tiddlymap...

**Comment by samuelwiechmann** [comment]
I just read through this post and stumbled over this:
@felixhayashi  commented on 26 Nov 2014:
> For example I plan in a private project to display nodes bigger based on their click-count; similar to a tag cloud

This is exactly what I already thought of for my current project. How would you realize this?

**Comment by flibbles** [comment]
The best vis-network can do is creating different node-types with different fontSize/widthConstraint.maximum settings. These are both configurable per node-type (just not through the configuration menu).

1. Create node types for a variety of different sizes.
2. Put fancy filters into their scope which considers "parent of", "child of", "# of clicks", etc...
3. For each node type, Edit the `style` field of `$:/plugins/felixhayashi/tiddlymap/graph/nodeTypes/$(node type)$`
    * The json you put is something like this: `"font":{"size":36},"widthConstraint":{"maximum": 800}}`

I realize it's not optimal to have "tiers" if different sizes, rather than just have the sizes be dynamic to some variable, but this is what you get. I'm closing this issue out again.
