### ISSUE TITLE
Default tags and node colours

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#133]
Would it be possible to specify a default tag and/or colour to be added to new nodes. This could be either from selection widgets on the toolbar or, more simply, by clicking a checkbox that indicates that you want to copy the format (tag, node colour) from the most recently created node.

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

Really great idea I have to say! I could add this to the "create new node" dialog that is opened when double clicking on the canvas to create a node. The last used color would be preselected and a list of existing colors in the wiki will be displayed as well.

Also: I am really planning to introduce #16 !

This would probably also solve your issue because it would be possible to define a rule "[tag[Literature]]" => color: blue.

(Using form elements of course!).

I am very busy with my work at university at the moment (my thesis) so I am sorry if development is currently slow. I always have to force myself not to work on TiddlyMap :D
-Felix

**Comment by Peter-Miller** [comment]
Your idea is the way to go. No pressure timewise -- I hope TidddlyMap is being useful for your thesis! Remember to keep a recent backup!

**Comment by felixhayashi** [comment]
> Your idea is the way to go.

I like yours as well, I think I'll implement them both as described above.

> No pressure timewise -- I hope TidddlyMap is being useful for your thesis! 

This was one of the reasons I invented it in the first place! :) It is useful, especially for organizing and keeping track of my overall thesis structure, especially how pieces of literature depend on each other. But just like you, I frequently stumble upon workflow issues that ask for some optimization.

> Remember to keep a recent backup! :)

Most certainly! :) Nothing worse than losing a day of work because of a system crash. I am doing rotating incremental backups on different external hard-drives every hour :D Better be on the safe side ;)

**Comment by felixhayashi** [comment]
Closed in favour of #16
