### ISSUE TITLE
Shift-drag to create new edge

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#134]
Is it possible to shift-drag or similar to create a new edge rather than clicking the Add Edge button first?

**Comment by felixhayashi** [comment]
That would be nice! I'll have a look at the vis.js docs. I do not think it is possible at the moment but I'll propose it to the guys at vis.js to have this implemented. If they do not want to support hotkeys, I'll think of adding it myself to TiddlyMap at some point.

Thanks for the idea @Peter-Miller

**Comment by tobibeer** [comment]
In case you were to create issues at the vis.js project, please put a link here.

**Comment by felixhayashi** [comment]
Sure, I'll do that. But maybe it is possible with the current means visjs provides. I'll need to check that but haven't found the time yet.

**Comment by danielo515** [comment]
I suppose that it would create a "node" with the same values and it will allow you to edit the title. If so :+1:

**Comment by felixhayashi** [comment]
> Is it possible to shift-drag or similar to create a new edge rather than clicking the Add Edge button first?

Hi @Peter-Miller 

I decided to use a different hotkey approach using ctrl+1/2. This way, you are even faster when the nodes are far away because you just have to select the nodes and press the hotkeys to connect them (without dragging). Please see: https://github.com/felixhayashi/TW5-TiddlyMap/issues/197#issuecomment-168402226. Hope that's fine with you (and everybody else).

-Felix

**Comment by Sitiyok** [comment]
+1

Am 02.01.2016 um 17:12 schrieb Felix Küppers:
