### ISSUE TITLE
List of existing connections

### ISSUE THREAD

**Issue by gabrixbr** [felixhayashi/TW5-TiddlyMap#138]
Hello Fellix!
First of all, congratulations on TiddlyMap. It is truly a amazing tool!

However, I have some questions:

In tiddler's map button there is a existing connection list:

1- Could this list be classified by connection type name? Imagine we have 100 connection of different types... If it is ordered by connection type it would be easier to find something.

2- Is there a way to put this (ordered) list withing the tiddler text? The graph is really a cool tool to reasoning but sometimes the old classified text could be better.

Thanks, 
Gabriel.

**Comment by felixhayashi** [comment]
Hi @gabrixbr 

> First of all, congratulations on TiddlyMap. It is truly a amazing tool!

Thanks, glad you like it!

> 1- Could this list be classified by connection type name? Imagine we have 100 connection of different types... If it is ordered by connection type it would be easier to find something.

This is not possible at the moment, I wanted to keep it simple (usually a tiddler does not have more than a few incoming/outgoing relationships) so I only included the type in brackets. But I plan to improve the quick connect button anyways so when working on it again, I'll definitely consider your case. Might take a while though because there is much stuff on the todo list ;) By the way, you could also use the live view for this...

> 2- Is there a way to put this (ordered) list withing the tiddler text? The graph is really a cool tool to reasoning but sometimes the old classified text could be better.

Yes such a widget exists :) But it is not "stable"(!) and highly unofficial(!) and it will certainly change (because it needs much improvement)! But if you want to experiment with it, please see this the comment I made here, which also contains a short example: https://github.com/felixhayashi/TW5-TiddlyMap/issues/119#issuecomment-95586589

-Felix
