### ISSUE TITLE
How to link tiddlers progragmatically

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#141]
Hi @felixhayashi 

I am writting a script to export my company's database to tiddlymap, so we at support have a better visibility of it.

I am trying to find the best way to do this as much automatically as I cant. The tricky part comes when I have to decide how to create the tables and properties tiddlers. If I tag all the properties with its table, then tiddlymap will relate them automagically. But I also want to show relations between tables, and this is done by showing the properties they have in common. At first I just though that I can tag each property with all the tables it appears at, but this have several disadvantages: It's hard to just add a tag to an already generated tiddler, I can't add the property description as tooltip. So I think it's better to create each property with its table as a prefix, and then relate each property "someway". Could you advise me in how to do this? How can I relate tiddlers before being added to tiddlymap? Can I name those relations?

Many thanks!

**Comment by felixhayashi** [comment]
Hola @danielo515 

> I am writting a script to export my company's database to tiddlymap, so we at support have a better visibility of it.

Nice :)

>  If I tag all the properties with its table, then tiddlymap will relate them automagically.

I would not use tags for that because a tag could mean anything and do not necessarily mean "attribute of". To increase the semantics I would use an edge-type called "attribute of".

> But I also want to show relations between tables, and this is done by showing the properties they have in common.

If it's a relational db, a common attribute does not necessarily mean it is a foreign key... Two tables may have an attribute "creation date" or "id" which does not make them related. Better be explicit.

> It's hard to just add a tag to an already generated tiddler

The following should work (not tested though). Or maybe I misunderstood you?

```javascript
var tObj = $tw.wiki.getTiddler("XYZ");
var newTags = [ "dfg", "hah" ]; 
newTags.push.apply(newTags, tObj.fields.tags || [])
$tw.wiki.addTiddler(new $tw.Tiddler({ title: XYZ, tags: newTags}));
```

> I can't add the property description as tooltip

Once I finish migrating to vis v4 we can add the edge-type descriptions as tooltips :) -> #140


> So I think it's better to create each property with its table as a prefix,

That sounds like a good idea, also because it will look nicely ordered in the search results!

> and then relate each property "someway". Could you advise me in how to do this? 

I think what you need is to use TiddlyMap's adapter api. The adapter object is available via `$tw.tmap.adapter`. You can have a look at the adapter functions online. For example the `$tw.tmap.adapter.insertEdge()` function allows you to insert an edge from everywhere: http://wkpr.de/hosting/tmp/tw5/tiddlymap/api/module-TiddlyMap-Adapter.html#insertEdge.

Before you use `insertEdge`, you may need to create the nodes via `insertNode`: http://wkpr.de/hosting/tmp/tw5/tiddlymap/api/module-TiddlyMap-Adapter.html#insertNode

Does this help?

Maybe have a look at an example at the start page of the api docs: https://bitly.com/tiddlymap_api

-Felix

P.S. I realized that the API docs are **not** complete because I changed much in the last time. So I need to document it again. But the two functions I mentioned above should work as documented...

**Comment by danielo515** [comment]
> I would not use tags for that because a tag could mean anything and do not necessarily mean "attribute of". To increase the semantics I would use an edge-type called "attribute of".

Yes I agree.

>>It's hard to just add a tag to an already generated tiddler
>The following should work (not tested though). Or maybe I misunderstood you?

Yes you did :smile: 
What I want is to create a bunch of tiddlers from a dump file from the DB. At first instance I just wanted to create a script that generates tid files or tiddlywiki.files file. Now I'm thinking about creating a deserializer module. But your suggestion requires tiddlymap plugin to be loaded and accessible while processing the input file.

I have to parse the resultant file to identify foreign keys, but I would like to add that information as metadata of tiddler filelds. Creating nodes and edges seems very complicated and not a task to do at once.

From your suggestion I think what I have to do is to get the file (not sure how), parse it and create an array of tiddlers. Then what? create a node per each tiddler? But how can I then relate the foreign keys? take in account that when importing the dump file the foreign keys tiddlers may not exist already. I was thinking in something like tags works currently: you tag a tiddler with a tag, and when that tag is created it appears magically on tiddlymap and it is related with the tiddler that contains it. How can I achieve a similar behavior?

Thanks felix.

**Comment by felixhayashi** [comment]
I thought so :) but I think I got it now :) (maybe :D)

> Then what? create a node per each tiddler?

A tiddler is automatically regarded as node in TiddlyMap if it has an `tmap.id` field.

> But how can I then relate the foreign keys?

When creating a tiddler from the db dump, create a field `tmap.id` with a lowercase uuid as value (see my code for the code that generates uuids..).

e.g: `tmap.id: 10af4ba7-306f-4e68-9e32-d0342d64a717`

Then have a look at how tiddlymap stores the edges. It uses a field `tmap.edges`. So first create another tiddler which contains a unique `tmap.id` field and also an `tmap.edges` json-field of the following structure:

```javascript
[25209609-d1c8-44a4-8f31-f5dbf6c85098]: { // a random(!) edge id
  "to": [10af4ba7-306f-4e68-9e32-d0342d64a717],
  "type": "foreign key reference"
}
...
```

Save the json via `JSON.stringify()`.

> take in account that when importing the dump file the foreign keys tiddlers may not exist already.

Doesn't matter ;) if you link to a non-existent id, it will be ignored. If a tiddler with this id will be created later on, it will be immediately recognized by tiddlymap.

Was this a better answer?

-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

> Then have a look at how tiddlymap stores the edges. It uses a field tmap.edges. So first create another tiddler which contains a unique tmap.id field and also an tmap.edges json-field of the following structure:

I am a bit confused about this step. Do you mean that I have to create a tiddler for the edge? And then on the tiddler that I want to link i have to create a field with that values? An array as property name, an array as to property and a string which is the name of the type. Is that correct or have I messed something?


> Doesn't matter ;) if you link to a non-existent id, it will be ignored. If a tiddler with this id will be created later on, it will be immediately recognized by tiddlymap.

The problem is: how can I know the uuid of a tiddler that does not exist yet ?

Thank you very much!

**Comment by felixhayashi** [comment]
Hi @danielo515 

> I am a bit confused about this step. Do you mean that I have to create a tiddler for the edge?

No. Edges are always stored in the tiddler from which the come from. So if you have a Tiddler A and a connect it to a Tiddler B and name the relation XY then TiddlyMap will make sure A and B have tmap.id set to a unique value and it will store the relationship into tiddler A. Just go to the tiddlymap demo site and see which fields are created when creating an edge between two new tiddlers.

> An array as property name, an array as to property and a string which is the name of the type. Is that correct or have I messed something?

Almost. It is not an array it is an object that looks like this:

```
{
  "d4ca6750-780f-4640-b8fa-fa2efa449c92": {       <-------- random uuid as edge-id
    "to": "fa8c4f3e-b216-4744-b65c-5335f02f66a9",  // Id of tiddler A
    "type": "rel-1"
  },
  "97345e5b-505d-4625-8843-5169b7fda209": {
    "to": "7017feb5-3955-464b-a4b5-a22a420ab828", // id of tiddler B
    "type": "rel-2"
  }
}
```

Result:

![selection_359](https://cloud.githubusercontent.com/assets/4307137/8135663/450eb3ae-1139-11e5-9200-123270ce4aca.png)

> The problem is: how can I know the uuid of a tiddler that does not exist yet ?

You can decide yourself which uuid to give to a tiddler. Simply create a tiddler that already has a field `tmap.id` set to a value and tiddlymap will accept it and not override it.

Hope it helps. Otherwise keep asking ;)

**Comment by danielo515** [comment]
Hello @felixhayashi, 

Your answers are always helpful. But I still have a couple of doubts. Should each relation type have the same uuid or each relation has it's own ID? Your example has two different types, so I can not deduct from it 😜

>Simply create a tiddler that already has a field tmap.id set to a value and tiddlymap will accept it and not override it.

That's fine for the Tiddlers that I am creating, but a FK tiddler may exist already (so I have to check on every tiddler process) or can not exist and will not be created because is not part of the table being imported. Of course I can create it beforehand but then it will get overrided wen I import the table that contains it. That is my actual problem. One possible solution is to create all the Tiddlers, and before returning the array of processed tiddlers check if any of them exists and merge them. What do you think? Is there a better solution like uuid prediction /reservation?

**Comment by danielo515** [comment]
Hello again, 

I just realized that what I'm asking is exactly how is tagged works. You put the destination tiddler and when it exist it is magically linked. Why not allow this behavior for other custom fields? Just creating a special tiddler that specifies that a new automatic relation exists. What do you think?

**Comment by felixhayashi** [comment]
Hola

> Should each relation type have the same uuid or each relation has it's own ID? 

Each edge has a unique uuid to make it truly unique. The "type" of a relation is referenced by its name.

So `d4ca6750-780f-4640-b8fa-fa2efa449c92` is the edge id, and "rel-1" is the type. You can always add edges (with a different edge ids) that are of the same type!

{
  "d4ca6750-780f-4640-b8fa-fa2efa449c92": {       <-------- random uuid as edge-id
    "to": "fa8c4f3e-b216-4744-b65c-5335f02f66a9", <-------- Id of tiddler A
    "type": "rel-1"
  },
  "97345e5b-505d-4625-8843-5169b7fda209": {
    "to": "7017feb5-3955-464b-a4b5-a22a420ab828", <-------- id of tiddler B
    "type": "rel-1" <-------------------------------------- now also of type rel-1
  }
}

Then both edges (one to A and one to B) would be of type "rel-1" and both be of color red if the style of "rel-1" is set to be red (see below). So the edge-type is like a "class" and the edge itself is like an instance. To make sure the instance is unique it needs a uuid so when Tiddlymap needs to remove or change the edge or its type, it knows how to find the edge.

The "style" of an edge is specified in the edge-type.

Types are stored below `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/`.

Here stuff like description, style, label etc. is stored.

Have a look at: `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tmap:link`

The user uses the Edge-type manager to edit edge-types (see Part 1 of my youtube video "TiddlyMap Basics").

The style field is stored as json.

At the moment vis.js v4 is out and I am still using vis v3.12 so some styles of their website do not work...

> I just realized that what I'm asking is exactly how is tagged works. You put the destination tiddler and when it exist it is magically linked.

This is why Jeremy did not use uuids :D But as you know this comes at a high cost: The problem here is that this operation is based on tiddler **titles**! So yes, it will be magically linked when you tag it but everything will break if a title is changed. But you can do the same for uuids as I already described. You create edges that link to another tiddlers `tmap.id` and when a tiddler with that `tmap.id` exists it is magically linked.

So I think your idea -- *One possible solution is to create all the Tiddlers, and before returning the array of processed tiddlers check if any of them exists and merge them.* -- is reasonable.

> Why not allow this behavior for other custom fields?

You mean like this? https://github.com/felixhayashi/TW5-TiddlyMap/issues/129

---

I think I could better help you if you describe the actual workflow

> What I want is to create a bunch of tiddlers from a dump file from the DB.

Are you periodically saving db dumps to tiddlywiki?

> Your answers are always helpful. But I still have a couple of doubts.

Thanks. If you think it is easier to solve this issue in a face to face discussion, send me a mail and we could do a quick hangout...

-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

Thank you very much for the advises you gave me the other day in our hangouts conversation. I am implementing them with partial success. 
I am using the UUID directly from tiddlymap, so I do $tw.tmap.utils.genUUID() and it works flawlessly.

My problem is that edges are not shown on any view unless I create a tiddler of that type manually. I think I have to create a tiddler with prefix "$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes" to make my own edge types visible. In fact, I can't think in any way of showing the edges unless I create a tiddler that contains references that edge.

Any advise in this topic is welcome.
Regards.

**Comment by danielo515** [comment]
It was as I though.

Making sure to add a tiddler with the prefix I mentioned plus the edge name make it appear auto-magically. Now I want to decide if I want to have this on the default view or If if want to create a specific view for this. Thank you very much! I feel like this issue is resolved.

**Comment by felixhayashi** [comment]
Hi @danielo515 

> Making sure to add a tiddler with the prefix I mentioned plus the edge name make it appear auto-magically. 

Nice!!

> Now I want to decide if I want to have this on the default view or If if want to create a specific view for this.

I would highly recommend the following: Add a namespace to all edges that are related to the db-topic (http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Edge-type%20namespaces). e.g. `db:foreign key` or `db:attribute` and then you can always decide later to create a view that only displays these types by changing the edge-type filter of the view to: `[prefix[$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/db]]`

The namespace is not visible to the user of tiddlymap but you can see it in the edge-type manager.

-Felix

> Thank you very much! I feel like this issue is resolved.

No problem, great to see tiddlymap in use and to have had a chat with you :)

**Comment by danielo515** [comment]
>I would highly recommend the following: Add a namespace to all edges that are related to the db-topic 

Yes, I was thinking about doing it. I was deciding the prefix to use. Maybe I will use offline: and onlline: or db-offline and db-online because we have two types of DBs. Or maybe including both DBs on the same wiki is to much for any compute. Anyway, this is resolved. Thank you! But don't forget to add the functionality we have discussed, whenever you have time.

**Comment by felixhayashi** [comment]
> Anyway, this is resolved

Okay

> But don't forget to add the functionality we have discussed, whenever you have time.

Aye!

**Comment by tobibeer** [comment]
Regarding https://github.com/felixhayashi/TW5-TiddlyMap/issues/141#issuecomment-111241301:

> The following should work (not tested though).

Mhhh, doesn't quite... it deletes any other fields. 8-O
