### ISSUE TITLE
vis capabilities to arrange graphs

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#164]
Perhaps you already know or not whether vis can layout nodes in graphs depending on edge-types, i.e. aggregated... and perhaps with different "layout modes" per edge-type.

I was just revisiting http://www.thebrain.com and they display three main types of edges for a centered node...

* **node > child-nodes**
    * below the node, evenly distributed into strains bottom-left and bottom-right
* **node > parent-node > node-siblings**
    * the parent to the top, forking to a column to the right to list siblings
* **node > jump-node**
    * to the left, evenly distributed into strains to left-top and left-bottom
    * more losely tied nodes, not hierarchical, e.g. a related "user"

This seems to make for a very powerful note-taking experience... and so I was wondering if vis would allow such ways to layout the graph, that is ...to have different layout modes for edge-types such as the above.

For example, one could use two custom tag-like-fields to model the relationships, e.g.

* parents (implies children, could be default tags field)
* related (to have a separate list from the above)

Another question would be what happens in terms of siblings if a node had two parents.

**Comment by felixhayashi** [comment]
Hi @tobibeer 

thanks for sharing this info. TheBrain seems to be a great tool.

> Perhaps you already know or not whether vis can layout nodes in graphs depending on edge-types, i.e. aggregated... and perhaps with different "layout modes" per edge-type.

I think this issue is related to #13. The thing is that vis/tiddlymap does not give special meaning to edges and interpetes edges all the same. Put otherwise, it does not come with a predefined ontology that includes hierarchical notions (taxonomies) like "child-parent", "class-subclass" or "is a" or other relations like "uses" or "property of" etc. Nor does it come with any axioms to check whether such relations are consistent. For example you could draw "Node A is parent of Node B" and at the same time "Node B is parent of Node A" and it would still be cool.

So at the moment, TiddlyMap does not differentiate between edges and is not aware of any special meaning. Making TiddlyMap aware of special node relations would be a huge task and would require much additional work (e.g. axioms/rules to ensure integegrity).

So I guess this is a nofix for now :(

-Felix

**Comment by tobibeer** [comment]
Wasn't planning on putting anything on your tada-list ;-)

More of an informative inquiry whether you know if something like this was possible at all with vis... and only later with TiddlyWiki.

By the way, integrity ain't as important so long as the graph won't scramble to pieces due to it, i.e. has meaningfull conflict handling.

**Comment by felixhayashi** [comment]
> Wasn't planning on putting anything on your tada-list ;-)

I don't mind if you do, I am always happy if somebody comes up with ideas ;) Of course in the end I'll cherry-pick what I like :D

> More of an informative inquiry whether you know if something like this was possible at all with vis... and only later with TiddlyWiki.

Vis is totally agnostic to special kind of relationships.

> By the way, integrity ain't as important so long as the graph won't scramble to pieces due to it, i.e. has meaningfull conflict handling.

Yap. But meaningfull conflict handling is already complicated enough ;) (recursion protection etc.)

**Comment by tobibeer** [comment]
With no actionables in sight...
