### ISSUE TITLE
View and Edit Relationships from Within a Tiddler

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#19]
Idea:

Have a field that lists existing relationships to other tiddlers and allows you to add/remove relationships.

**Comment by tobibeer** [comment]
I guess with "field" you mean a section in the relationships popup, right?

![popup](https://cloud.githubusercontent.com/assets/97566/5593178/f623ccaa-91fb-11e4-9469-12f718ad4a48.gif)

**Comment by felixhayashi** [comment]
Hi @andtheWings,

not quite sure what you mean. This feature already exists and if you look at tobi's screenshot you can see the link connection wizard. Click it and you will see:

![selection_417](https://cloud.githubusercontent.com/assets/4307137/5593890/e3192386-922c-11e4-8b9b-f02bb6f5cc7d.png)

and zooming...

![selection_418](https://cloud.githubusercontent.com/assets/4307137/5593892/f16e277e-922c-11e4-8f35-fa17b562e293.png)

You can click on the edit icon (top left) and add or delete edges).

-Felix

**Comment by tobibeer** [comment]
@felixhayashi, not sure if the graph is always the best representation to show connections, though. Sometimes a plain, filterable list feels a lot more efficient... especially for a popup-ui. I know, this is all about graphs. Just raising the question if an alternative, simple view may not be beneficial here and there, especially when looking at / starting from a single node.

**Comment by felixhayashi** [comment]
@tobibeer,

> Sometimes a plain, filterable list feels a lot more efficient

Really true. Thought the same. But it was cheep for me to recycle the graph editor instead of programming another way to do it (and I am really short of time at the moment). Maybe if this https://groups.google.com/d/topic/tiddlywiki/KakzBdIhywY/discussion will make it somehow and I could trigger actions more easily, I rewrite it.

**Comment by tobibeer** [comment]
> really short of time at the moment

Take all the time you need. No pressure form my end.

**Comment by andtheWings** [comment]
Sorry for not responding right away. My original thought was to have a textual field sort of like:
>**Tiddler Relationships:**
>- **Link Type 1:** "Tiddler A", "Tiddler B", "Tiddler C"
>- **Link Type 2:** "Tiddler B", "Tiddler D", "Tiddler E"
>- etc.

But yeah, no pressure from my end to make this sort of change right away.

**Comment by tobibeer** [comment]
@andtheWings — if I get you right that won't be possible, because **Link Type 1** is not a valid fieldname. It would only be a valid JSON property... but then that's how they're perhaps stored anyway.

**Comment by andtheWings** [comment]
@tobibeer Sorry I just used Link Type 1 as a generic stand-in title. Perhaps I should have said edge_type_1 or something. Basically what I'm envisioning is there might be a tab in the info section of the tiddler where a list of other tiddlers connected to it would be listed, being sorted by edge type. Ideally you would be able to textually edit the relationships too without having to use the graph interface. I'm still not sure if I'm using the right terms. Does this make better sense? I'm basically agreeing with you that a plain filterable list would be more efficient in certain contexts.

**Comment by felixhayashi** [comment]
@andtheWings,

ah ok now I understand what you mean.

**Comment by tobibeer** [comment]
Yes, that makes it clear and it is surely desireable. A bit like a TiddlyMap info panel making use of some TiddlyMap-macro or -widget that outputs wiki contents rather than a graph, e.g. lists.

**Comment by felixhayashi** [comment]
By the way TiddlyMap now has a live view on its right side (its the tab next to "editor"). When you scroll it changes (using the diving mode). While this does not solve this issue here, it certainly helps viewing the neighbors of the currently focussed (scrolled to) tiddler.

-Felix

**Comment by andtheWings** [comment]
Thanks for the heads up!

**Comment by felixhayashi** [comment]
no problemo :)

**Comment by felixhayashi** [comment]
Hi @andtheWings, @tobibeer

I changed the in-place quick connect mechanism. You can best see the effect if you have the live view open at the same time.

![selection_471](https://cloud.githubusercontent.com/assets/4307137/5988097/ff04aa7c-a94f-11e4-8962-d5ca471429c5.png)

Let me know, what you guys think or if you have ideas for improving the mechanism.

-Felix

**Comment by tobibeer** [comment]
Nice. However, with respect to which **view** are we doing this? It seems we're always doing it globally.

**Comment by andtheWings** [comment]
Don't the connections exist regardless of what view you are using?

**Comment by andtheWings** [comment]
The change is definitely an improvement. I updated my [biochem wiki](http://danielriggins.com/biochem) if you want to take a look at how I'm using your plug-in.

**Comment by Peter-Miller** [comment]
That's a great application, Daniel, and one I'm interested in myself. Is there any way you can link from the tiddler to the map, i.e. zoom to the relevant node?

**Comment by felixhayashi** [comment]
> Nice. However, with respect to which view are we doing this? It seems we're always doing it globally.

@tobibeer Yes, well spotted :) The reason is, I wanted to keep it simple. I actually tried hard to somehow integrate the private mode in the "quick connect" mechanism but it gets really messy: I need to show only views that operate in private edge mode in a dropdown (otherwise it would not make sense), then I also need to display only private edges  of that view in the edge-dropdown above instead of global edges, then I need to explain to the user what is the difference between private and public edges.

So now I decided to use the TiddlyMap button exclusively for global relations. The private edge mode is activated from the editor and should be regarded as tool when building mind maps (which is done in the editor as you would normally also build a mind map when using a tool like e.g xmind).

@andtheWings Wow, really impresive! I will show this to a friend who studied pharmacy and who lately asked me how the plugin could be used ;)

> Don't the connections exist regardless of what view you are using?

No, I made an attempt to improve the documentation to clarify this issue. Please see "Public and Private Edges" and  "Configuring the current view" in the docs on the demo site.

@Peter-Miller

> Is there any way you can link from the tiddler to the map, i.e. zoom to the relevant node or set it to the focus?

Actually it would be a great addition, to create an option for the live view where instead of showing the neighbourhood, all nodes and edges are shown and the graph is only zoomed to the node which is currently focussed. Then you could also zoom outside to see the bigger picture. Have to think about that.

**Comment by andtheWings** [comment]
@felixhayashi Thanks for the documentation. I think I understand now.

**Comment by tobibeer** [comment]
> Yes, well spotted :)
> The reason is, I wanted to keep it simple.

I thought so. ^^

> I need to show only views that operate in private edge mode in a dropdown

Yes, so the first option would be "global", perhaps some separator and then all views in private ege mode.

> then I also need to display only private edges of that view in the edge-dropdown above instead of global edges

yes

> then I need to explain to the user what is the difference between private and public edges

in any way, I think that is an important distinction to know

> I decided to use the TiddlyMap button exclusively for global relations. The private edge mode is activated from the editor and should be regarded as tool when building mind maps (which is done in the editor as you would normally also build a mind map when using a tool like e.g xmind).

I think that is a sensible approach. However, I would add some hint at the connection wizard that reminds the user that this is indeed the case... perhaps creating an awareness of how there is a different mode indeed doing so.

**Comment by felixhayashi** [comment]
> I think that is a sensible approach. However, I would add some hint at the connection wizard that reminds the user that this is indeed the case... perhaps creating an awareness of how there is a different mode indeed doing so.

Yes, I agree. I already rewrote the docs to create this awareness and maybe it is good to add a small hint in the "quick connect" drop down as you suggested that references the online docs so the user can inform him- or herself.

**Comment by andtheWings** [comment]
Some more thoughts after using the new connection wizard a couple days:

1. It's actually a little harder to remove existing connections than it was before. It can't be done from within the connection wizard or live view. I need to find the connections within the "map" tab on the right. I still like the current form of the connection wizard much better, but it would be nice if it included a means to edit and remove existing connections. 
2. I keep expecting to be able to close the connection wizard when I click somewhere else on the page. I can see how it's nice to be able to use other aspects of the wiki while keeping the wizard open, but it'd not intuitive to me (I know I'm being nitpicky). I'm not sure if this would be any better or not, but what if instead of being a hovering widget over the tiddler, the connection wizard was a tab within the info section of the tiddler. The drawback would be that this would make it more hidden than it currently is. Just a thought.

**Comment by tobibeer** [comment]
> I keep expecting to be able to close the connection wizard when I click somewhere else on the page.

:+1: 

> it would be nice if it included a means to edit and remove existing connections

:+1: removing might be simpler though ;-)

I'm not really sure if we're talking about a "mere" connection wizard though.

Isn't it rather a "Where is this tiddler represented in a TiddlyMap?" wizard with all the wizardry to add and edit all that, and navigate-to, e.g. focus the graph viewer to a particular node, even edge?

**Comment by felixhayashi** [comment]
> It's actually a little harder to remove existing connections than it was before. It can't be done from within the connection wizard or live view.

Good point.

> I need to find the connections within the "map" tab on the right.

Yes, that's annoying

> I still like the current form of the connection wizard much better, but it would be nice if it included a means to edit and remove existing connections.

Since there may be several connections between two nodes, I cannot simply add a remove button to the dropdown next to each entry in the list (next to the "from" and "to" buttons) - how should I know, which edge to remove? Maybe displaying all the existing edges in the dropdown with a cross (to delete the edge) is an option. That way, it would be also possible to see existing connections when not being in the live view or when working with a mobile phone having a small display. I have to further think about that.

> removing might be simpler though ;-)

Yes, I think I cannot support editing an edge from the dropdown (reconnecting, changing edge properties). This would make everything too complicated.

> I keep expecting to be able to close the connection wizard when I click somewhere else on the page. I can see how it's nice to be able to use other aspects of the wiki while keeping the wizard open, but it'd not intuitive to me (I know I'm being nitpicky)

Yes, this is also somewhat annoying to me and I never liked it but there is currently no way to prevent this in tiddlywiki. I could use the button and the reveal widget in popup mode but then it would also close as soon as you click somewhere in the dropdown. Therefore I force the dropdown to stay open by explicitly toggling the state, to ensure it does not close when you e.g. click in the the dropdown's search box.

On the other hand it has one advantage. Imagine you add many edges, then it would be annoying to always open the dropdown again - now you can just click on the "from" and "to" buttons as often as you like, thus quickly creating connections. Maybe I could add a click listener at the time the dropdown opens, which listens if you click outside the dropdown and then removes the dropdown again. I think this could work. Generally I think it would be the right thing to add a pull request to tiddlywiki's repo that adds a //widget option// that a popup may stay open until clicked outside.

> I'm not sure if this would be any better or not, but what if instead of being a hovering widget over the tiddler, the connection wizard was a tab within the info section of the tiddler. The drawback would be that this would make it more hidden than it currently is. Just a thought.

While this is a creative suggestion, I really think it should stay accessible as it is.

> Isn't it rather a "Where is this tiddler represented in a TiddlyMap?" wizard with all the wizardry to add and edit all that, and navigate-to, e.g. focus the graph viewer to a particular node, even edge?

Since you guys both mentioned it in a way, how about a search field in the editor's topbar that could work the following way:

1. when you start typing, a dropdown list with all tiddlers (nodes) currently displayed in the graph is displayed.
2. When you click on a title in the dropdown list, the viewport will slowly start to focus the node, probably starting to zoom a bit.

This will make it much easier to work with large networks (as Daniel already does) in the editor.

-Felix

**Comment by tobibeer** [comment]
> Maybe displaying all the existing edges in the dropdown with a cross (to delete the edge) is an option.

Not sure what you mean with "dropdown". I'd show a flat list of all existing connections at the bottom of the wizard, with **from** or **to** and **type** ...and that remove button ...**from** and **to** not being **buttons** here.

Theoretically you could show existing connections and those to-be connected in the same list, but you would also have to show the connection type once created... and perhaps show existing connections at the bottom so as to have the once to be selected for creation up top.

> Yes, this is also somewhat annoying to me and I never liked it but there is currently no way to prevent this in tiddlywiki.

Perhaps formulate a [new issue](https://github.com/Jermolene/TiddlyWiki5/issues) to at least have a reminder / indicator of this problem and get to work on solutions. There possibly needs to be an option to make a popup "sticky" so that it doesn't close when clicked inside but always closes when clicked outside. The default would be that it closes when clicked inside, e.g. a link in a tag-popup.

> Maybe I could add a click listener at the time the dropdown opens, which listens if you click outside the dropdown and then removes the dropdown again.

> Generally I think it would be the right thing to add a pull request to tiddlywiki's repo that adds a //widget option// that a popup may stay open until clicked outside.

I agree, this definitely is core territory. While you could do this yourself, I recommend you don't.

> Since you guys both mentioned it in a way, how about a search field in the editor's topbar that could work the following way:

How is that different from using the standard search? Wasn't there something like that already? Perhaps not duplicate things... maybe you could even hook into the search process and have it show your popup below the default search box, both opening the tiddler as well as centering it in your graph.

This also smells like core territory whereas there could be said popup to quickly open a tiddler by a given title and then a way to hook into the "open this tiddler" event... which you already do leverage using that dynamic mode of yours, I reckon.

**Comment by felixhayashi** [comment]
> Not sure what you mean with "dropdown". I'd show a flat list of all existing connections at the bottom of the wizard, with from or to and type ...and that remove button ...from and to not being buttons here.

Yes, this is what I meant ;)

> Perhaps formulate a new issue to at least have a reminder

yeah

> I agree, this definitely is core territory. While you could do this yourself, I recommend you don't.

Yes

> How is that different from using the standard search? Wasn't there something like that already? Perhaps not duplicate things... maybe you could even hook into the search process and have it show your popup below the default search box, both opening the tiddler as well as centering it in your graph.

The graph search that currently still exists sucks at the moment and I think of removing it completely... What I have in mind is totally different, it is a "zoom function" when inside the editor, it is not really meant to behave like a tiddler search (I think we are talking about different things here). I implemented a prototype (see demo and screenshot).

![selection_473](https://cloud.githubusercontent.com/assets/4307137/6022223/a48aee1c-abbb-11e4-90c5-eb2d3c86f488.png)

**Comment by tobibeer** [comment]
I see. I tried a global search for "icon" and I can see what you perhaps mean with "it sucks". Searching for "pitfall" doesn't look to bad though. I guess the problem is when you have a number of matches, then things just look scrambled.

I would agree that it's possibly more important to have the graph keep up with the navigation history. If I open a bunch of tiddlers and then click the graph tab it would show me the last opened tiddler / or currently viewed one. Oh, I just noticed you've split out the live graph (or was it always separate?!?)

Anyhow, that mockup definitely looks, works quite well and makes a lot of sense. It should perhaps also close when clicked outside. ;-)

For the time being, thank you for all the effort you putting into this. :+1:

**Comment by andtheWings** [comment]
I like the prototype search bar. Also ditto on the thank you. This plug-in is great.

**Comment by felixhayashi** [comment]
@tobibeer 

> That mockup definitely looks and works quite well and makes a lot of sense. It should perhaps also close when clicked outside. ;-)

Yes... I will work on a pull request for that desired popup behaviour :)

> I tried a global search for "icon" and I can see what you perhaps mean with "it sucks". Searching for "pitfall" doesn't look too bad though. I guess the problem is when you have a number of matches, then things just look scrambled.

Yes, that is the problem. Also you don't know why a node is displayed as no search term is highlighted (in contrast to google's result list or danielos context search).

> I would agree that it's possibly more important to have the graph keep up with the navigation history.

Yes I think this is really a strength of the plugin.

> If I open a bunch of tiddlers and then click the graph tab it would show me the last opened tiddler / or currently viewed one. Oh, I just noticed you've split out the live graph (or was it always separate?!?)

No you are correct, I split the two. I formerly called it "diving", you probably remember. Now it became the "live view" which synchronizes with the story river and is updated by the top-story-view plugin.

> For the time being, thank you for all the effort you're putting into this.

Well, you are also contributing a lot to the success of tiddlywiki, so thank you too :)

@andtheWings 

> I like the prototype search bar. Also ditto on the thank you. This plug-in is great.

Thanks for the positive feedback

I updated the tiddler-toolbar-dropdown (see demo): It now contains a very basic "remove list" (It's kept simple on purpose). Please let me know, what you guys think

![selection_475](https://cloud.githubusercontent.com/assets/4307137/6071519/13f39164-ad97-11e4-9058-ad4f243b93dc.png).

Regards
Felix

**Comment by felixhayashi** [comment]
@danielo515, I remember you once asked for a better way to connect tiddlers in the google groups, so maybe this update is also interesting for you? I would be happy to hear your opinion.

**Comment by andtheWings** [comment]
I like it! Seems like you added all the features I asked for when originally opening the issue. :)

**Comment by tobibeer** [comment]
Thanks, @felixhayashi... that's quite the connection wizard.

**Comment by felixhayashi** [comment]
> I like it! Seems like you added all the features I asked for when originally opening the issue. :)

Yeah, long journey :)

> Thanks, @felixhayashi... that's quite the connection wizard.

Thanks Tobi

**Comment by danielo515** [comment]
Hello @felixhayashi 

Thank you for keeping me updated about this. I think the new system is definitively an improvement and I can not envision any better system. I strongly think that as important as having the information is to link the topics that are related, and this helps in this task. 

Thank you

**Comment by felixhayashi** [comment]
Thanks @danielo515 for your feedback. Your opinion is much appreciated :)
