### ISSUE TITLE
Images not displayed correctly

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#218]
> Hi Felix,
> 
> thanks again for the great plugin. Now I have an issue:
> 1. Situation:
>    I have a tiddlymap with tiddlers being displayed
>    Each tiddler has an icon, the name is stored in a field "icon"
>    The image (svg) is stored in a plugin
> 2. Outcome: the icons do not appear in the map, the nameof the tiddler 
>    is displayed as simple text (no tag-pill)
> 3. Question: Can it be that tiddlymap does not find icons which are 
>    stored in a plugin(shadow)?
> 4. Observations:
>    4.1 if I have an empty field "icon", I get the same effect
>    4.2 if I delete the field "icon", tiddlymap shows  a tag-pill
> 
> Is this normal? Or do I maybe have an issue with my infrastructure 
> (Firefox, hardware, software?)
> 
> Thanks again.
> 
> Pit

@Sitiyok

**Comment by felixhayashi** [comment]
Hi Pit,

Strange, TiddlyMap usually has no problems of showing svg images that come as plugins. Which plugin are you using that contains the svg? Can you create a minimal wiki demo of what is not working? Otherwise I cannot debug this…

-Felix

P.S. I deleted your post at #217 and created a separate issue for this problem. Please create new issues for new problems.

**Comment by Sitiyok** [comment]
Dear Felix,

thanks for this lightning-fast reply!

1. I use a selfmade plugin, made with Tinka.
2. I have meanwhile found out, png are displayed, svg not, no matter if 
plugin/shadow, system or standard

I run my wiki under node.js, with nearly 1.000 tiddlers in the system 
and shadow area and 3.000 in standard.  So creating a minimal version 
wouldnt help, since minimalzing might also remove the cause of the 
undesired behaviour.

maybe its something about my firefox...

I will have to find out myself, Your time is too precious, and you 
already helped me.

Thanks again for all the things you do for the community

Pit

Am 04.04.2016 um 19:54 schrieb Felix Küppers:

**Comment by felixhayashi** [comment]
> I have meanwhile found out, png are displayed, svg not, no matter if plugin/shadow, system or standard

Ah ok, so it is a problem with svg. Maybe you could export an svg that is not displayed from your plugin as *.tid file and attach it to this issue in a post (drag n drop) so I can have a look at it?

> I will have to find out myself, Your time is too precious, and you already helped me.

Thanks for being considerate but don't hesitate to ask questions if something is not working.

-Felix

**Comment by Sitiyok** [comment]
Dear Felix,

this is the culprit from the plugin.

Kind regards,

Pit

Am 04.04.2016 um 20:27 schrieb Felix Küppers:
>
>     I have meanwhile found out, png are displayed, svg not, no matter
>     if plugin/shadow, system or standard
>
> Ah ok, so it is a problem with svg. Maybe you could export an svg that 
> is not displayed from your plugin as *.tid file and attach it to this 
> issue in a post (drag n drop) so I can have a look at it?
>
>     I will have to find out myself, Your time is too precious, and you
>     already helped me.
>
> Thanks for being considerate but don't hesitate to ask questions if 
> something is not working.
>
> -Felix
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/felixhayashi/TW5-TiddlyMap/issues/218#issuecomment-205436042>
>



created: 20150308165032961
modified: 20160229173116179
revision: 0
title: $:/+PGA/admin/country/img/flag.svg
type: image/svg+xml

<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="22px" height="22px" viewBox="0 0 30.09 30.089" style="enable-background:new 0 0 30.09 30.089;"
	 xml:space="preserve">
<g>
	<g>
		<g id="Icons_1_">
			<path d="M28.75,11.658l-3.483-10.96c-0.149-0.473-0.623-0.764-1.113-0.685L18.84,0.88c-1.121,0.183-2.202,0.628-3.125,1.289
				L13.262,3.92c-0.893,0.638-1.945,0.988-3.042,1.013L5.943,5.03c0.134-0.442,0.141-0.929-0.01-1.402
				c-0.396-1.25-1.731-1.942-2.982-1.544C1.699,2.481,1.009,3.815,1.406,5.066c0.225,0.704,0.75,1.223,1.388,1.477l7.15,22.5
				c0.203,0.639,0.793,1.046,1.43,1.046c0.149,0,0.304-0.021,0.455-0.071c0.79-0.251,1.227-1.094,0.976-1.884L9.579,17.986
				l4.168-0.094c1.5-0.031,2.938-0.512,4.16-1.384l2.451-1.752c0.677-0.482,1.467-0.809,2.285-0.942l5.313-0.867
				c0.287-0.047,0.539-0.217,0.689-0.464C28.801,12.235,28.837,11.934,28.75,11.658z M13.702,15.894l-4.364,0.099L6.485,7.018
				l3.778-0.084c0.577-0.013,1.14-0.11,1.689-0.253l2.878,9.056C14.462,15.824,14.087,15.885,13.702,15.894z M16.745,14.881
				c-0.304,0.217-0.631,0.387-0.967,0.536l-2.876-9.051c0.531-0.217,1.046-0.479,1.521-0.817l2.453-1.752
				c0.122-0.087,0.251-0.163,0.38-0.239l2.866,9.02c-0.321,0.165-0.634,0.344-0.927,0.553L16.745,14.881z M22.322,11.841
				c-0.436,0.071-0.859,0.193-1.275,0.34l-2.878-9.057c0.322-0.119,0.654-0.215,0.994-0.271l4.46-0.729l2.871,9.033L22.322,11.841z"
				/>
		</g>
	</g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

**Comment by felixhayashi** [comment]
Hi @Sitiyok,

seems like you are right, it is not working. Strangely, other svg are working fine. Moreover, your svg is displayed correctly outside TiddlyMap. Maybe it is a visjs problem. I am not sure how to fix this at the moment. Anyhow, once there is progress on this issue, I will post it here.

-Felix

**Comment by Sitiyok** [comment]
Hi Felix,

I did some testing and is seems that in Version 0.10.2+7002 SVG-icons 
are still displayed correctly in Tiddlymap

Pit.W

Am 05.04.2016 um 22:25 schrieb Felix Küppers:

**Comment by sepremento** [comment]
Have same issues here. Custom SVG-icons do not show properly. Same thing: no tag-pills, no icons. Core SVG-icons, .png and .jpeg seem to work ok though. TiddlyWiki v5.1.22, TiddlyMap v0.17.4+9899.

Plugins except TiddlyMap:
- relink v1.5.3
- Project Manager v0.0.45 (+datepicker v0.5.2 + moment v2.24.0)
- edit-comptext v0.9.0
- KaTeX v5.1.22
- preview v0.5.6 (+appear v0.6.2)

**Comment by onlyice** [comment]
Get the same problem here.

I import this SVG file ([link](https://github.com/felixhayashi/TW5-TiddlyMap/files/5101377/database.zip)) as a tiddler with a `image/svg+xml` type. It can be displayed as a tiddler icon, but can not be displayed in TiddlyMap.

When I enabled verbose output of TiddlyMap, some error shows in the console:

```
Could not load image: data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve"> <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="99.2515" y1="282.3497" x2="408.2476" y2="282.3497" class="gradient-element"> 	<stop offset="0" class="primary-color-gradient" style="stop-color: #FCCF31"></stop> 	<stop offset="1" class="secondary-color-gradient" style="stop-color: #F55555"></stop> </linearGradient> <path fill="url(#SVGID_1_)" d="M256.4,448.3l-99.8-10.5c-15.9,0-30.2-6.4-40.6-16.8c-10.3-10.2-16.7-24.4-16.8-40.1 	c-0.3-31.9,26.6-42.3,58.4-42.3l98.9,2.4c34.4,0,62.4-50.1,62.4-84.5v-78.3c0-34.4,27.9-51.4,62.4-51.4l26.9-11v268.7 	c0,27.2-22,49.2-49.2,63.9H256.4z M256.4,448.9"></path> <path d="M256.4,456.9c-57.1,0-94.1-8.4-115.2-15.5c-16.4-5.5-43.8-17.3-43.8-34.5V113.6c0-1.3,0.3-2.4,0.8-3.5 	c-0.5-1.6-0.8-3.3-0.8-5.1c0-17.2,27.4-29,43.8-34.5c21-7.1,58.1-15.5,115.2-15.5c57.1,0,94.1,8.4,115.2,15.5 	C388,76,415.4,87.8,415.4,105s-27.4,29-43.8,34.5c-21,7.1-58.1,15.5-115.2,15.5c-57.1,0-94.1-8.4-115.2-15.5 	c-8.1-2.7-18.9-7-27.8-12.7v78.9c0.3,1.8,7.5,11,35.2,19.9c19.9,6.4,54.7,14,107.8,14c53,0,87.9-7.6,107.8-14 	c27.5-8.9,34.8-18,35.2-19.9v-58.7c0-4.4,3.6-8,8-8s8,3.6,8,8v159.5c0,0.1,0,0.1,0,0.2c-0.4,17-28.1,28.7-44.5,34.2 	c-21.1,7-58.1,15.4-114.4,15.4c-56.3,0-93.3-8.4-114.4-15.4c-8.3-2.8-19.5-7.1-28.5-12.9v79c0.2,1.7,7.2,10.9,34.5,19.8 	c19.8,6.4,54.7,14.1,108.5,14.1s88.7-7.7,108.5-14.1c27.3-8.9,34.2-18.1,34.5-19.9l0-58.7c0-4.4,3.6-8,8-8s8,3.6,8,8V407 	c0,17.2-27.4,29-43.8,34.5C350.6,448.5,313.5,456.9,256.4,456.9z M113.5,306.3c0.3,1.8,7.5,11,35.2,19.9c19.9,6.4,54.7,14,107.8,14 	c53,0,87.9-7.6,107.8-14c27.5-8.9,34.8-18,35.2-19.9v-79c-9.1,5.8-20.2,10.2-28.5,12.9c-21.1,7-58.1,15.4-114.4,15.4 	c-56.3,0-93.3-8.4-114.4-15.4c-8.3-2.8-19.5-7.1-28.5-12.9V306.3z M113.5,105c0.4,1.9,7.5,11,34.5,19.8 	c19.8,6.4,54.7,14.1,108.5,14.1s88.7-7.7,108.5-14.1c27-8.8,34.1-17.9,34.5-19.8c-0.4-1.9-7.5-11-34.5-19.8 	c-19.8-6.4-54.7-14.1-108.5-14.1S167.8,78.7,148,85.2C121,94,113.9,103.1,113.5,105z"></path> <path fill="#000000" d="M463.9,252.6c0,4.4-3.6,8-8,8h-43c-4.4,0-8-3.6-8-8s3.6-8,8-8h43C460.3,244.6,463.9,248.2,463.9,252.6z 	 M434.4,274.6h-73.8c-4.4,0-8,3.6-8,8s3.6,8,8,8h73.8c4.4,0,8-3.6,8-8S438.8,274.6,434.4,274.6z M483.5,53h-15.8V37.2 	c0-4.4-3.6-8-8-8s-8,3.6-8,8V53H436c-4.4,0-8,3.6-8,8s3.6,8,8,8h15.8v15.8c0,4.4,3.6,8,8,8s8-3.6,8-8V69h15.8c4.4,0,8-3.6,8-8 	S487.9,53,483.5,53z M54.8,64h-3.9v-3.9c0-4.4-3.6-8-8-8s-8,3.6-8,8V64H31c-4.4,0-8,3.6-8,8s3.6,8,8,8h3.9v3.9c0,4.4,3.6,8,8,8 	s8-3.6,8-8V80h3.9c4.4,0,8-3.6,8-8S59.2,64,54.8,64z M50.2,203.2c-5.9,0-10.8,4.8-10.8,10.8s4.8,10.8,10.8,10.8s10.8-4.8,10.8-10.8 	S56.1,203.2,50.2,203.2z M50.2,273.2c-5.9,0-10.8,4.8-10.8,10.8s4.8,10.8,10.8,10.8s10.8-4.8,10.8-10.8S56.1,273.2,50.2,273.2z 	 M50.2,334.2c-5.9,0-10.8,4.8-10.8,10.8s4.8,10.8,10.8,10.8s10.8-4.8,10.8-10.8S56.1,334.2,50.2,334.2z"></path> <path fill="#FCCF31" class="primary-color" d="M458.4,429.2v-34.7H493v34.7H458.4z M493,481.4v-34.7h-34.7v34.7H493z M439.7,481.4v-34.7h-34.7v34.7H439.7z 	"></path> </svg>
```

It seems there's a duplicated definition of the `xmlns` field. But the original SVG file doesn't have duplicates. I suppose it's a Vis.js issue, but after some google search I found nothing.

**Comment by ahilliard** [comment]
This issue was gone for awhile, but seems to be back.  I set up a freshly-configured TiddlyWiki [tiddlymap_test.zip](https://github.com/felixhayashi/TW5-TiddlyMap/files/13537986/tiddlymap_test.zip):
- Core: $:/core 5.3.1
- tiddlymap: $:/plugins/felixhayashi/tiddlymap 0.17.16+10020
- vis-network: $:/plugins/flibbles/vis-network 9.1.3
- hotzone: $:/plugins/felixhayashi/hotzone 0.0.3
- topstoryview: $:/plugins/felixhayashi/topstoryview 0.2.0

I defined one tiddler to be shown in TiddlyMap with the core icon /core/images/tag-button .  The SVG renders fine in the story river but not in the vis.js view where only the tiddler name is shown as plain text.  In the console, the script $:/plugins/flibbles/vis-network/vis-network.min.js:33  throws the error:

`Could not load image: data:image/svg+xml;utf8,\parameters (size:"22pt") <svg xmlns="http://www.w3.org/2000/svg" width=<<size>> height=<<size>> class="tc-image-tag-button tc-image-button" viewBox="0 0 128 128"><g fill-rule="evenodd"><path d="M18.164 47.66l.004 4.105c.003 3.823 2.19 9.097 4.885 11.792l61.85 61.85c2.697 2.697 7.068 2.69 9.769-.01L125.767 94.3a6.903 6.903 0 00.01-9.77L63.928 22.683c-2.697-2.697-7.976-4.88-11.796-4.881l-27.076-.007a6.902 6.902 0 00-6.91 6.91l.008 9.96.287.033c3.73.411 8.489-.044 13.365-1.153a9.702 9.702 0 0111.14-3.662l.291-.13.128.285a9.7 9.7 0 013.3 2.17c3.796 3.796 3.801 9.945.012 13.734-3.618 3.618-9.386 3.777-13.204.482-5.365 1.122-10.674 1.596-15.309 1.237z"/><path d="M47.633 39.532l.023.051c-9.689 4.356-21.584 6.799-30.396 5.828C5.273 44.089-1.028 36.43 2.443 24.078 5.562 12.976 14.3 4.361 24.047 1.548c10.68-3.083 19.749 1.968 19.749 13.225h-8.623c0-4.859-3.078-6.573-8.735-4.94-6.91 1.995-13.392 8.383-15.694 16.577-1.915 6.818.417 9.653 7.46 10.43 7.126.785 17.531-1.352 25.917-5.121l.027.06.036-.017c1.76-.758 6.266 6.549 3.524 7.74a2.8 2.8 0 01-.075.03z"/></g></svg>`

**Comment by flibbles** [comment]
That's probably because the image file now has that `\parameters ...` pragma in it, which makes it no longer a pure svg image. If you remove that pragma, and replace all the instance of the `<<size>>` variable with "22pt", maybe it'll work? Dunno.

TiddlyWiki v5.3.x broke a bunch of stuff, so I'm not surprised that it's messing up something like this.

**Comment by flibbles** [comment]
It's pretty clear that the core team aren't going to fix this. They're married to the new `\parameter` nonsense.

So I went ahead and made a new TMap release that copes with that. Icons should work again for v0.17.18.
