### ISSUE TITLE
Broken fields resulting from multiline text when creating edges

### ISSUE THREAD

**Issue by VicDemos** [felixhayashi/TW5-TiddlyMap#237]
Good day! 
I have an error. 
1. Start using tiddlywiki Node.js. 
2. Set tiddlymap plugin.
![image 1](https://cloud.githubusercontent.com/assets/21632415/18164491/c947aa30-7048-11e6-9d90-e833b37467da.png)

3. After restarting the server the error occurs. 
![image 2](https://cloud.githubusercontent.com/assets/21632415/18164500/d4a091f8-7048-11e6-8eba-c010208c7614.png)
![image 3](https://cloud.githubusercontent.com/assets/21632415/18164501/d75f1ec8-7048-11e6-8192-9b42bfae1f49.png)

Is there a solution to this error?

**Comment by felixhayashi** [comment]
Snap. Thanks for telling me @VicDemos 
This was introduced with v0.11.3 and results due to TiddlyWikis inability to handle multiline field strings in nodejs mode. I think you can quickfix this by opening the tiddler  `$:/plugins/felixhayashi/tiddlymap/config/sys/user`
and add:

    jsonIndentation: 0

But I'll do a real bugfix soon.
