### ISSUE TITLE
Don't update View's node filter if unnecessary

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#285]
I accidentally hit the enter key while typing in the title, so this posted before I was even able to make the body. Filling it out now...

Whenever you add a node to a view, the ViewAbstraction adds it explicitly to it's node filter in the form of `[tmap.id[...]]`. This works fine, but it's been problematic for me because I don't really explicitly add nodes to my views. My node filters are custom-made, and usually look something like:

```
[prefix[foo/]]
[[foo]]
[tag[tags/graph/foo]]
## And other custom filter stuff
```

And when I add `foo/newTitle` to a graph, it is unnecessarily added to the node filter by it's ID, which means it doesn't disappear nicely if I change my node filter. It also clutters up my git commits (which I use to version my projects)

But if we changed ViewAbstraction##addNode to:
```javascript
  addNode(node) {

    if (!this._isNodeIncludedById(node)) {

      // Single new line of code here
      if (this.getNodeFilter('compiled')().indexOf(node.label) == -1) {

        const part = ViewAbstraction._getNodeIdFilterPart(node);
        const separator = ' ';
        this.setNodeFilter(this.getNodeFilter('raw') + separator + part);

      }

      this.saveNodePosition(node);

    }

  }
```

Then it will detect if a new node is already included by a custom node filter.

I know I use TiddlyMap differently than everyone else, but I think this wouldn't conflict with anyone who only has hand-built views instead of procedurally-built views like I do. But if you don't think this would be a good direction to go, that's fine. I can always just keep the change on my fork.

But if you like, I can make a PM.

**Comment by felixhayashi** [comment]
Hi @flibbles 

> And when I add foo/newTitle to a graph, it is unnecessarily added to the node filter by it's ID, which means it doesn't disappear nicely if I change my node filter.

I have a question because maybe this is a conceptual misunderstanding: Why would you need to add a node to a graph via `addNode()` when it matches your node filter? Because if it matches your filter, it will simply be included in your map without further ado. `addNode()` is only meant to add nodes by id.

**Comment by felixhayashi** [comment]
Ah ok I understand. Back then I thought intensively about this behaviour and I felt it is not intuitive to the user if he/she added a node via click and it were not explicitly added with its id to the view. Because adding a node via double click means that the user actively decided to add it and it should be independent from all other filters in the map.

But I also understand your perspective. We could add this as a feature to tiddlymap, that is configurable in the global tiddlymap config. We don't need to write the GUI for this but can add this as a hidden config to the system, something like:

```
$tm.config.sys.alwaysAddNodeIdToViewFilter: true
```

```
  addNode(node) {

    if (!this._isNodeIncludedById(node) && $tm.config.sys.alwaysAddNodeIdToViewFilter) {

        const part = ViewAbstraction._getNodeIdFilterPart(node);
        const separator = ' ';
        this.setNodeFilter(this.getNodeFilter('raw') + separator + part);

      this.saveNodePosition(node);

    }

  }
```

The other changes you suggested are not necessary, if I am not mistaken, because the sole job we need to accomplish is to prevent the id from being written in the view.

What do you think?

**Comment by flibbles** [comment]
This would work fine. My use-case is pretty narrow. In fact, it's so narrow that it may just be worth keeping it on my own private fork instead of needlessly complicating TiddlyMap. However, if we do go forward with this, I think the code would look like this:

```javascript
  addNode(node) {

    if (!this._isNodeIncludedById(node)) {

      if ($tm.config.sys.alwaysAddNodeIdToViewFilter || this.getNodeFilter('compiled')().indexOf(node.label) == -1) {

        const part = ViewAbstraction._getNodeIdFilterPart(node);
        const separator = ' ';
        this.setNodeFilter(this.getNodeFilter('raw') + separator + part);

      }

      this.saveNodePosition(node);

    }

  }
```
It looks like `this._isNodeIncludedById(node)` only checks if the node is... well, included by Id, so it wouldn't pick up if it's factored in by custom filter bits. So unfortunately, I think the compiled filter does have to be run. `this.saveNodePosition(node)` needs to be included outside of that block, because otherwise when you perform the _double click and create_ action, the node shows up at the view's center, not where you clicked (assuming the node gets implicitly included). But it's inside the `if(this._isNodeIncludedById(node))` block, because if the node _was_ included by Id, then it must have already existed (and be included in the view), thus saving the Node's Position would only serve to move an already-included node around.
