### ISSUE TITLE
Making nodes not draggable

### ISSUE THREAD

**Issue by linsteina** [felixhayashi/TW5-TiddlyMap#293]
Hi @felixhayashi 
is it possible to make the nodes in a view not draggable? So the positions of the nodes are fixed, but still can be defined from the view json file. Thanks!

**Comment by felixhayashi** [comment]
Hi @linsteina, technically speaking, yes.

A question from my side: Do you also want to prevent people from drawing edges or adding new nodes to the map? So hiding all editing controls as e.g. in the [TaskManagementExample map](http://tiddlymap.org/#TaskManagementExample%202.0)? In this case, my second solution further below is more suitable.

So to answer your question:

When a [node is dragged](https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/js/widget/MapWidget.js#L2412), I [unfreeze it](https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/js/widget/MapWidget.js#L2418) by [calling a function](setNodesMoveable) `setNodesMoveable`.

To solve your use case, one could add a "guard" `this.view.isEnabled('read_only')`, e.g.

```
handleVisDragStart({ nodes }) {
    
  if (nodes.length && !this.view.isEnabled('read_only')) { <--- guard
    ...
    this.setNodesMoveable(nodes, true);
```

...and then have some kind of option in the interface (analog to "physics_mode" view setting) in the GUI:

![2018-08-16 14 51 52](https://user-images.githubusercontent.com/4307137/44209520-08214600-a164-11e8-9e8e-bb21c6a9a45e.png)

---

### Solution 2)

Second thought: I would much rather prefer to not add another option to the GUI and instead base the "guard" on whether tiddlymap [is rendered in editor mode](http://tiddlymap.org/#The%20widget's%20editor%20option) or not:

```
handleVisDragStart({ nodes }) {
    
  if (nodes.length && !this.editorMode) { <--- guard
    ...
    this.setNodesMoveable(nodes, true);
```

Remark: `this.editorMode` is `null` if no editor toolbar is shown.

This would effectively mean that if no editor bar is present, one cannot drag nodes.

If you want your [sidebar map editor](http://tiddlymap.org/#Sidebar%20map%20editor) to be read only, you would then need need to override [$:/plugins/felixhayashi/tiddlymap/hook/editor](http://tiddlymap.org/#%24%3A%2Fplugins%2Ffelixhayashi%2Ftiddlymap%2Fhook%2Feditor), **or** create another tab in tiddlywiki. Creating another tab is a better solution because if you override the sidebar editor, it will not receive tiddlymap version updates in the future anymore (because you overrode it).

If you are interested in creating a PR for the "Solution 2)" I would welcome it.

Best wishes

**Comment by linsteina** [comment]
@felixhayashi 
Yes to your question. So yes, the solution 2 is better. Thanks for your help! Creating a PR will be much helpful!
