### ISSUE TITLE
Importing edges from Excel spreadsheet?

### ISSUE THREAD

**Issue by ahilliard** [felixhayashi/TW5-TiddlyMap#310]
Similar to #60, #61, #141, and <a href="https://www.mail-archive.com/search?l=tiddlywiki%40googlegroups.com&q=Function+to+add+edges+in+Tiddlymap&submit.x=0&submit.y=0">previous mailing list questions</a>, I'm trying to import a previously-done [analysis](https://github.com/ahilliard/tiddlyWDA) into TiddlyMap.  Is there any method that could re-use existing XLSX import tools for Tiddlywiki?

My data are in an Excel export, as two tables:
Nodes:
- nodeID (unique)
- Type (text tag)
- Name, description (text)

Edges:
- edgeID (unique)
- From (nodeID)
- To (nodeID)
- Type (text tag)
- Description (text)

I've imported all 194 nodes using the [XLSX-Utilites](https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/xlsx-utils) plugin, and set names, descriptions, and tags with no problem.

Edges I have no idea how to do without <a href="https://www.mail-archive.com/tiddlywiki@googlegroups.com/msg87388.html">getting into</a> code (like <a href="http://tiddlymap.org/api/Adapter.html#insertEdge">$tm.adapter.insertEdge</a>)?  The XLSX utilities can set fields (like tmap.id UUID maybe?) but don't seem suited to generating more complex syntax like <a href="http://tiddlymap.org/#Storage%20of%20Edges%20and%20their%20types">tmap.edges</a>. It seems I need to:
 - Define edge-types in advance
 - Set a valid UUID on each node based on the Excel import ID
 - Generate tmap.id string(s) for each edge

or alternately
 - Import edgeID from / tos as a list field
 - Use <a href="http://tiddlymap.org/#tw-list">the tw-list: magic edge-type</a> to define edges?

Or else do it all by hand, but for 200 nodes and 600 edges I'd rather not. Could you please point me in the best direction?  Thank you for sharing all your amazing work on TiddlyMap.

**Comment by felixhayashi** [comment]
Hi @ahilliard , 
please excuse the very delayed response to this issue.

I think you evaluated the situation correct from every respect.

For edges to be imported into Tiddlywiki you need to "Define edge-types in advance" as you mentioned and then you need to create references (the actual edges) between nodes by storing the edge date in the node (=tiddler) that is the `from` part of the relationship.

So I think you got this right already and were looking at the right spots in the documentation.

> The XLSX utilities can set fields (like tmap.id UUID maybe?) but don't seem suited to generating more complex syntax like tmap.edges.

As you referenced, magic edge types allow you to avoid using TiddlyMap's native [json edge-type](http://tiddlymap.org/#Storage%20of%20Edges%20and%20their%20types) format and also to give edges an actual "id", instead relying on TiddlyWiki formats such as [tw-list](http://tiddlymap.org/#tw-field).

Otherwise, if your nodes and edges have ids and you want to keep this linkage via ids, your only option with Tiddlymap is to get into coding unfortunately (since you need to populate the json format) e.g. by using $tm.adapter.insertEdge and similar.

**Comment by ahilliard** [comment]
A colleague wrote a script tiddler to help with it, and it went well (a little finicky, but it only had to work once).  Looking forward to sharing the results soon.  Thanks again!
