### ISSUE TITLE
Tiddly Map automatic with fields

### ISSUE THREAD

**Issue by oChems** [felixhayashi/TW5-TiddlyMap#315]
Hey,

I am a chemist and have tiddly wiki for organising my reaction notes.
Now I wanted to visualise them with tiddly map.

I have the following setup:
Most of my Tiddlers are with the tag "Reactions"
These tiddlers have field called
startingmaterial
startingmaterial2
startingmaterial3
product
product2
product3

in these fields are compounds. e.G. Alcohol, Acid, Base

For Example I have reactions that transform Alcohol (startingmaterial) to Acids (product).

Now I would like to visualise this in a huge tiddly map, which should show me, how you can go from one starting material to another, etc. etc. The compounds used in some starting materials could be the products in a different reaction. I hope you get the point.

Is there now a way to setup a tiddlymap (automatically) which will create the mindmap combining my compounds.

Thank you in advaced! I hope you can help me.

**Comment by felixhayashi** [comment]
Hi @oChems 

if (a) the values in your fields are tiddler-references and (b) you are willing to use fields as links instead of the native TiddlyMap edge links (via unique ids) then you can use "magic edge types"

→ have a look at: http://tiddlymap.org/#Magic%20Edge-Type%20Namespaces

For example, create a magic edge type for field `startingmaterial` via `tw-field:startingmaterial` and it will be recognized as edge and if the value in `startingmaterial` is a tiddler it will be referenced in the map.

See also http://tiddlymap.org/#tw-field

**Comment by felixhayashi** [comment]
will close this issue now, feel free to continue commenting.
