### ISSUE TITLE
Tiddlymap does not respect Tiddlywiki timestamp setting

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#316]
If you turn off timestamps in Tiddlywiki, `modified`, `modifier`, `created`, and `creator` won't be set in tiddlers. I like this, since I version my tiddlywiki with git, and those fields would just be redundant.

However, Tiddlymap will still set a modified date in some circumstances. Particularly when you create a tiddler through double clicking on the graph.

Judging from the source code, this also happens when creating Snapshots, but I don't know anything about the feature, or how to utilize it.

Anyway, I've created a patch, which you may want to look at before accepting. I'll post the PR in a second.

**Comment by felixhayashi** [comment]
Hi @flibbles, many thanks for reporting this and your solution. I will take a closer look this weekend.

The main idea of the `touch` function is to set the modified date to the current date:

> The touch command is a standard command used in UNIX/Linux operating system which is used to create, change and modify timestamps of a file. 
> https://www.geeksforgeeks.org/touch-command-in-linux-with-examples/

Therefore, I would like to keep the behaviour of touch that it modifies the timestamp of the tiddler.

Would it be an option for you to instead of using `setField(tRef, 'modified', new Date());` in touch, we simply merge the existing tiddler with a new tiddler object and set `$tw.wiki.getModificationFields()`? I think this will already solve your problem since [judging by the source code](https://github.com/Jermolene/TiddlyWiki5/commit/d1121787c090ec8f5fc592b83c3dbad1075fe0ec#diff-3378be2ff14e6ff5521c34b06144efebR253), it will respect your "disabled timestamps settings in Tiddlywiki".

**Comment by flibbles** [comment]
That way does make more sense. I've modified my PR to reflect the changes. (Though I still have no idea how to test snapshots)
