### ISSUE TITLE
Feature, ".SVG output from TiddlyMap"

### ISSUE THREAD

**Issue by christalleras** [felixhayashi/TW5-TiddlyMap#332]
Currently TiddlyMap outputs to Png and JSON, but being able to do it in .SVG would be pretty neat as well as an option for some TiddlyWiki projects.

**Comment by felixhayashi** [comment]
Hi @christalleras 
unfortunately, the network on the HTML5 canvas is itself not drawn as svg and therefore cannot be exported as such easily.
Please see https://github.com/almende/vis/issues/723#issuecomment-83088006

Exporting the nodes to json and then turing it into a dot format then converting to svg is doable (https://github.com/almende/vis/issues/1784) but requires a server and since Tiddlywiki is serverless, this is doesn't seem possible.

**Comment by christalleras** [comment]
Oh, I see. Makes sense.
Thanks for putting in time to answer me!

**Comment by felixhayashi** [comment]
marked as wontfix since this is too hard to achieve and most likely will not give correct results.
