### ISSUE TITLE
can not see the button of save & exit when i want manage edge-types or node-types

### ISSUE THREAD

**Issue by inforabbi** [felixhayashi/TW5-TiddlyMap#341]
![Image of bug](https://github.com/inforabbi/mypictures.github.io/raw/master/img/bug%20of%20tiddlywiki%20map.png)

**Comment by inforabbi** [comment]
my tiddlywiki theme is the http://slidesnstories.tiddlyspot.com/

**Comment by Bearboat** [comment]
Good Morning and thank you for TiddlyMap! 
I have a similar problem. I don't get to see the OK and CANCEL buttons. So I can not use TiddlyMap at all. Is there a workaround or something that I have to install other than the normal setup procedure?
![No button OK or CANCEL](https://user-images.githubusercontent.com/63224583/78528054-c6cd2680-77de-11ea-92fb-374c4af295ba.png)
Best regards...

**Comment by felixhayashi** [comment]
Many thanks for reporting, which browser (+version) and which TiddlyWiki version are you using?

**Comment by felixhayashi** [comment]
I now also created a fresh installation in the latest TiddlyWiki and all looks fine...

:thinking: 

![2020-04-06 23:28:39](https://user-images.githubusercontent.com/4307137/78606957-785f6c80-785e-11ea-8240-94a4a0401dec.png)

**Comment by Bearboat** [comment]
Moin Moin felixhayashi,
Thanks for your prompt reply. I sometimes do use Firefox 56.0b9 (64-Bit) with the Tiddlyfox Plugin and mostly Tiddlydesktop 0.0.13 (13). More often than not I am working with my iPad using Quine 2 wich works great. I found out that the missing buttons in TiddlyMap are a problem of the individual TiddlyWiki that I am in (I use several). I have one TiddlyWiki that I named Zettelkasten. If I open TiddlyMap in there I see the buttons. In both of my everyday Tiddlywikis (work and private) I don't see them. They are all on TiddlyWiki ver. 5.1.21 and TiddlyMap ver. v0.16.1+9773. Maybe other plugins are causing a conflict (using Tekan - Kanban on both wikis that don't show the buttons). Last but not least it could also be settings and / or shadow tiddlers that have been changed along the line.
Thanks for looking into that problem - regard from Hamburg ;-)

**Comment by Bearboat** [comment]
Just to clarify - the problem exists in all the different browsers, Tiddly desktop and Quine 2. I first realized it in Quine and thought ist is because of working with the IPAd - but found it the same in all the other tools. Maybe you have a suggestion how to make a clean install of TiddlyMaps again.
Brg.

**Comment by felixhayashi** [comment]
Moin Moin :)
I have the same feeling that it is either a conflict with existing plugins or some system tiddlers have been overridden (through "shadow tiddlers").

However, if other plugins somehow changed the way dialog buttons are displayed, this problem cannot be fixed within TiddlyMap :(

Since the buttons at the bottom are broken, maybe check if you can see buttons for non-TiddlyMap related modals at all → import these tiddlers...

* https://tiddlywiki.com/#Modals 
* https://tiddlywiki.com/#SampleWizard

...into your wiki and click on the "open modal" button in the Modals tiddler.

If you cannot see a close button in your modals, this means modal buttons are entirely broken in your wiki, which is unrelated to TiddlyMap most likely.

Another issue may be that another plugin is overriding css styles and thus hiding the modal buttons :man_shrugging: .

> Maybe you have a suggestion how to make a clean install of TiddlyMaps again.

In your TiddlyWiki you can check via the advanced search (then going to the "shadows" tab) if for the namespace `$:/plugins/felixhayashi/tiddlymap` some system TiddlyMap tiddlers exist that have been locally overridden by you (those that are overridden appear **not** in bold font), then you can decide to simply delete the shadow tiddlers to restore the original state of TiddlyMap after installation. 

Afterwards you can remove TiddlyMap by removing the 4 plugins mentioned in the installation, save the wiki and install them again. 

Views, edges and nodes will persist in your wiki even after unistallation, so they will still be found in your wiki after reinstallation (I may fix this in the future if I find the time).

Hope this helps
Good luck :)

**Comment by inforabbi** [comment]
i solve my question eventually，i delete this plugin：$:/plugins/tesseract/tekan
it's ok！
![Image of bug](https://github.com/inforabbi/mypictures.github.io/raw/master/img/button.png)
![Image of bug](https://github.com/inforabbi/mypictures.github.io/raw/master/img/delete.png)
now i can see the OK and CANCEL buttons again
thanks all！

**Comment by Bearboat** [comment]
Thanks felixhayashi and inforabbi. This is how problems are solved 👍
I also deactivated the Tekan plugin an - what shall I say - problem solved. Again thanks stay healty!

**Comment by joshuafontany** [comment]
I also noticed this problem with Tekan. I am working on an update of it
that does not hide all modal controls & allows better flexibility in what
is shown in the "card" modals.... (alongside like 3 other TW projects
lol... including the Editiin I want to use Tekan & Tiddlymap together in,
so it may be a few weeks until a release).

Best, Joshua F

**Comment by felixhayashi** [comment]
That's good news. Thanks everybody for the feedback :+1: 

> I am working on an update of it that does not hide all modal controls

sounds great :+1: I know it can be quite challenging not to break other people's stuff when developing plugins :wink: E.g. At one point I started prefixing/scoping all my TiddlyMap css to avoid conflicting with other people's css layout.
