### ISSUE TITLE
Simple Question, Excluding Tiddly from automatically being linked to another Tiddly in the mindmap because it's tagged.

### ISSUE THREAD

**Issue by Momyr** [felixhayashi/TW5-TiddlyMap#385]
I want to create a nice looking mindmap detailing character relationships for my D&D setting. I have character tiddlys with nice tokens but then i also have lore document tiddlies aimed at that character. I would like to not have the lore documents not show up on my mindmap or alternatively not have them linked to the characters despite them being tagged to them. 

Does anybody have any ideas? I'd greatly appreciate it.

**Comment by flibbles** [comment]
This is super old, but I only took over recently. You can change the node filters on your map views to exclude certain types of tiddler (i.e. Lore documents). Getting only certain tag relationships to appear (character to character) but not others (character to lore) on the same view is outside the scope of TiddlyMap. But working with various views, you can probably get a workable result.

I'm going to close this unless you reply with a followup, because I suspect you don't even care anymore.
