### ISSUE TITLE
How can I see a map of all tiddlers, including those with no connections?

### ISSUE THREAD

**Issue by prehensileBBC** [felixhayashi/TW5-TiddlyMap#395]
I have a TiddlyWiki which isn't very large, and in which the nodes/tiddlers tend to cluster - I'll see 'knots' of densely connected nodes, with no links between clusters.

Obviously, generating maps of the knots is quite easy by traversing the connections from one member node, but I'd like to be able to see a map of _everything_ in my my wiki - so I can see all of the knots, even if they're not connected to anything else. Currently I hack this by having one node which _everything_ links to, and so traversing with no limit generates a map of everything, but that makes the maps messy.

I feel like I could do this with the correct filter syntax in View configuration -> Edit filters, but I'm new to TiddlyWiki and I can't really grok what the correct filter notation would be.

**Comment by Semmu** [comment]
Hi,

Since views can be based on dynamic [filters](https://tiddlywiki.com/static/Filters.html), if you write a filter, which returns all your notes, you can accomplish this. And luckily there is the [`all`](https://tiddlywiki.com/static/all%2520Operator.html) filter exactly for this.

So just create a new view, set the filter to `[all[tiddlers]]` and there you have it!

**Comment by flibbles** [comment]
He is correct. This solution should be suitable. Closing the issue.
