### ISSUE TITLE
Enable TiddlyMap to use ControlPanel's Themes and Palette selections

### ISSUE THREAD

**Issue by angrystatic** [felixhayashi/TW5-TiddlyMap#415]
Any chance to get TiddlyMap to follow the ControlPanel's Theme and Palette color scheme?
Some of TiddlyMap's color's seem to be hard coded.

**Comment by flibbles** [comment]
If you're still interested, what colors would you like to see change with the theme?

**Comment by angrystatic** [comment]
What I was interested in was having the TiddlyMap mirror whatever selection was possible from the theme chosen in the ControlPanel.

Whatever the background colour for the tiddlers are for a Dark Theme for example.

**Comment by flibbles** [comment]
With the latest release (v0.17.15), TiddlyMap will now do a lot better to blending in with whatever current palette you have enabled. It's not a *perfect* job, because I didn't make individual palette keys for all of the particular TiddlyMap colors, but if anyone wants to customize their aesthetic to that degree, they can open another issue.

Let me know if you experience any problems with this, otherwise I'm closing out this issue.

Just a note, this release, like all the latest ones, is only available through github.
