### ISSUE TITLE
Don't add tmap id

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#418]
This is avoidable I think. These id sometimes make errors when using template, which will copy a tiddler and its fields to a new tiddler. https://talk.tiddlywiki.org/t/apply-template-to-your-new-tiddler-a-template-list-plugin/2121

**Comment by flibbles** [comment]
You'd think it's avoidable, and I looked into the possibility of making tmap.id assignment lazy, but I can't. It's too ingrained into TiddlyMap, and I'm not familiar enough with the plugin to confidently make this change without introducing bugs.

If it were up to me, I'd just change TiddlyMap such that it never assigned tmap.ids, and it'd just use tiddler titles. There's enough infrastructure in TiddlyWiki for TiddlyMap to manage renames, and [I'm probably the most experienced person in the world to get that right](https://github.com/flibbles/tw5-relink).

Since felix isn't really around anymore, and I don't think he's returning, I'm going to close this issue, but I'll leave you with this. If you can, whever you're copying your templates, you might include the action:
```
<$action-deletefield $tiddler=<<newTiddler>> tmap.id />
```
Which will wipe that field before committing. This isn't great, but unless I'm prepared to really start carving into TiddlyMap, it's the best you can get.

**Comment by joshuafontany** [comment]
> Since felix isn't really around anymore, and I don't think he's returning, I'm going to close this issue, but I'll leave you with this.

Hey @flibbles I've noticed you take over maintaining this repo. I'd be down to do a deep-dive/rewrite of Tiddlymap - maybe a few months down the road.

**Comment by flibbles** [comment]
Yeah, it's definitely tempting, isn't it? If I had my way, there are a ton of ways I'd do TiddlyMap differently. The more I work on it, the more I'm inclined to just make my own TiddlyMap, which would be decentralized, lighter weight, and probably rely more on TiddlyWiki to do things (like use lists and filters to hold data instead of json, and rely on the widget refresh mechanism to detect change rather than build one from scratch.)

But oh yeah. It'd be a monumental amount of work which felix already did for us. I wonder sometimes if it might be better to fork this repository than to keep steering a little bit more away from his vision.
