### ISSUE TITLE
Bug: Map zooms out when the search bar is toggled off.

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#42]
This is using TiddlyMap 0.6.4+1802 on Firefox in Windows 7.

I can search for something in the map tab on the right side and the map will zoom in. But when I toggle the search button to make the search bar disappear, the map zooms out again. It would be nice if it maintained its zoomed in position.

**Comment by tobibeer** [comment]
:+1: sure thing

**Comment by felixhayashi** [comment]
Well, I did it on purpose. So when exiting the "focus mode" everything is reset. I did this because the map widgets embedded in tiddlers do not display the graph buttons or listen to keyevents/mousevents (only after a click on the graph) and thus you couldn't zoom out again, which is annoying (e.g. go to the "TaskManagement 2.0 example", focus, and imagine it wouldn't zoom out again after you close the dropdown, you would be stuck with no way to zoom out).

A compromise would be to insert a list item or button to the "focus button" dropdown list that says "zoom out" but this makes the list larger and is not as intuitive as simply closing the focus mode to reset the zoom. 

So there is a pro and a con to that behaviour. Couldn't you just leave the "focus mode" active (= drop down list displayed) until you finished your activity or does it hinder your work?

-Felix

**Comment by tobibeer** [comment]
Maybe one way would be to have clicking the search icon to close zooms out whereas clicking anywhere else keeps the graph as is.

**Comment by andtheWings** [comment]
I see your intention now. I would just label the search icon now to make its purpose more clear. Like perhaps next to the search icon it could say "toggle focus mode". I know it adds to clutter, but the behavior didn't feel intuitive when I first started using it.

**Comment by felixhayashi** [comment]
> Maybe one way would be to have clicking the search icon to close zooming things back out whereas clicking anywhere else keeps the graph as is.

Good idea.

> I know it adds to clutter, but the behavior didn't feel intuitive when I first started using it.

I am going with tobi's suggestion for now. I try to keep it zen-like (emphasis on "trying" ;) ).

Anyway the new commit does what you want I think...

**Comment by andtheWings** [comment]
Ooh, I like this a lot. Good call @tobibeer.
