### ISSUE TITLE
Warning: Global assignment detected [ '__core-js_shared__' ]

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#454]
https://github.com/tiddly-gittly/TidGi-Desktop/issues/385
https://github.com/tiddly-gittly/TidGi-Desktop/issues/460

```
Warning: Global assignment detected [ '__core-js_shared__' ]
```

I think this is related your build process (that add the core-js)

Maybe you can try https://github.com/tiddly-gittly/Modern.TiddlyDev for the build, which works very well for tons of our plugins.

**Comment by flibbles** [comment]
This is likely caused by vis-network.
Unfortunately it relies on global assignment to perform a certain task.
Unfortunately it's a 3rd party library that doesn't see much love these days, so I doubt I could convince them to change it.
Unfortunately TiddlyWiki made a change recently so that Global assignment warnings get printed out like this. At least it's better than what they originally made, which was to make TiddlyWiki crash if global assignment is detected. I had to fight for that.

I don't know if there's anything else I can do for this except that the warning will continue to exist in the browser console for the foreseeable future.

**Comment by linonetwo** [comment]
Yes, it is not crashing anymore, better than last versions. I think it is accept able now, these warnings won't be seen by the user, only show in the log.
