### ISSUE TITLE
tiddlywiki collapse after updating from 0.17.8 to 0.17.18

### ISSUE THREAD

**Issue by king0billy** [felixhayashi/TW5-TiddlyMap#455]
![image](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/b55fcc9d-60d3-4ccd-8413-ef0d80f54ff6)

![image](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/e422d332-52d9-461c-ab09-e8c787347fbd)

![image](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/82360691-57e2-49d2-b437-1e8cb1cae4e4)

**Comment by flibbles** [comment]
Hello! Sorry you're experiencing trouble.

I need more than this to go on.

I don't know what that last image is from. What do those red lines mean? Did you get an exception or something?

**Comment by king0billy** [comment]
The last picture is a comparison of different files between the two versions, via Beyond Compare.

exception as below: 
https://private-user-images.githubusercontent.com/52921954/333781690-226d81e3-38bc-44a0-be2a-d2662473df71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDY1NTgsIm5iZiI6MTcxNjgwNjI1OCwicGF0aCI6Ii81MjkyMTk1NC8zMzM3ODE2OTAtMjI2ZDgxZTMtMzhiYy00NGEwLWJlMmEtZDI2NjI0NzNkZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEwMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2N2ZjNGFlMTZmYTQyNzc5YjNlMTg4YjAwNjI4MmY1NGI5NWQ2NmYxNGJjYWIyMjQ5MTQ2NDBjYTVjNDA0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u58-cQT79R0akmYB8nGeC9N2cPmoeDjrLDbNie8J-nI

**Comment by flibbles** [comment]
It might work better if you drag the exception screenshot into github here like you did the other images. I'm not able to access the link you sent. My browser seems to think that there's nothing at that address.

**Comment by king0billy** [comment]
![ManicTime_Screenshot_2024-05-25_17-30-44_10-00_2520_1680_8960025_0](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/1519eef2-1784-4fdf-a323-344d8c17c165)

**Comment by flibbles** [comment]
I don't suppose I could bother you for a stack trace to go along with that? That'll be in the browser console after the exception happens.

Is it something you do that causes this exception to occur, or is it when the page loads?

If you'd like, and if you're able to give me your wiki file, I could determine these things for myself.

**Comment by king0billy** [comment]
![image](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/8db2d752-1cbf-4108-9aa2-b2507786ee2a)
[

https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/fbeffea9-2898-4cc6-b34b-557727e13314

](url)

**Comment by king0billy** [comment]
Here is all the tidders for test:  https://1drv.ms/u/s!AkIa8srN94mPg7QObwS5QH3wrzH0pA?e=Hfgtdt

**Comment by flibbles** [comment]
@king0billy I'm not sure you exported those tiddlers correctly. That has every plugin, AND every single shadow tiddler exported into that.

Did you use some kind of filter to select those in order to filter out your content? Because if so, you need to make sure you're not including shadow tiddlers.

I tried working with the dataset you included anyway. You have a breathtaking number of plugins installed. Over 53Mb of plugins alone?!?! I encountered hard crashes at every step trying to work with it. From trying to import it, or load it with the old Tiddlymap.

Also, it looks like a ton of the plugins you have depend on TiddlyMap, and influence it in some way. If I just import your Tiddlymap plugins, and then upgrade them, I don't get any errors.

If you can give me a json file that doesn't have your shadow tiddlers, maybe I might be able to at least point out what plugins TiddlyMap is conflicting with.

**Comment by flibbles** [comment]
Just to mention, I'm still trying. I'm approaching this from the exception trace now.

**Comment by king0billy** [comment]
a json file that doesn't have my shadow toddlers:  https://1drv.ms/u/s!AkIa8srN94mPg7RPyxuyIoNnlOS3sg?e=IlT1fW

**Comment by king0billy** [comment]
I would be very grateful if you could find the reason for the static HTML export error 

https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/23beb38f-67b2-489b-8ed6-bf5a61defc9e

**Comment by flibbles** [comment]
All right. Try upgrading to 0.17.19 instead. It should work.

(Or at least not crash at *that* particular spot.)

**Comment by flibbles** [comment]
> I would be very grateful if you could find the reason for the static HTML export error

I looked into this briefly. It's not a TiddlyMap error. That stack trace leads into the `danielo515/ContextPlugin`, which I've never heard of. That project may be able to help you if you submit a bug report there.

**Comment by king0billy** [comment]
> All right. Try upgrading to 0.17.19 instead. It should work.好的。请尝试升级到 0.17.19。它应该有效。
> 
> (Or at least not crash at _that_ particular spot.)（或者至少不会在那个特定的地方崩溃。）

thank you very much!  It works now!

**Comment by king0billy** [comment]
> > I would be very grateful if you could find the reason for the static HTML export error如果您能找到静态 HTML 导出错误的原因，我将不胜感激
> 
> I looked into this briefly. It's not a TiddlyMap error. That stack trace leads into the `danielo515/ContextPlugin`, which I've never heard of. That project may be able to help you if you submit a bug report there.我对此进行了简短的研究。这不是 TiddlyMap 错误。该堆栈跟踪通向 `danielo515/ContextPlugin` ，我从未听说过。如果您在那里提交错误报告，该项目可能会对您有所帮助。

After I disable danielo515/ContextPlugin, I can export any tiddlers. But if I want to export  [all[shadows]]，an error will be reported Uncaught TypeError: Cannot set property parentNode of #<Node> which has only a getter

![image](https://github.com/felixhayashi/TW5-TiddlyMap/assets/52921954/b756239b-de8a-4a06-a256-b9ca3ae22ff0)

**Comment by flibbles** [comment]
I don't know. That problem looks like it's coming from `oeyoews/codemirror`. You'd need to speak with them.

I'm going to close this issue, since the TiddlyMap-related bug has been resolved. I can appreciate that you're having trouble with your TiddlyWiki being unstable. You have 154 plugins installed. But it's not my place to help you with issues that aren't related to TiddlyMap.

I wish you luck in troubleshooting your TiddlyWiki. You'll need it. I found isolating bugs in your tiddlywiki to be a daunting challenge.
