### ISSUE TITLE
RSOD with TW v5.3.5-pre - missing type

### ISSUE THREAD

**Issue by pmario** [felixhayashi/TW5-TiddlyMap#457]
@flibbles -- There has been a [Talk thread](https://talk.tiddlywiki.org/t/please-help-final-checks-for-bug-fix-release-v5-3-5/10104/9?u=pmario), where etardiff points out a problem with TiddlyMap. 

I did find the issue and I think why it happened. The problem is caused at: https://github.com/felixhayashi/TW5-TiddlyMap/blob/2f0a2779c342a3bf1b9e91539296b07b023391d3/src/plugins/felixhayashi/tiddlymap/js/edgeTypeSubscriber/AbstractRefEdgeTypeSubscriber.js#L65 because the type: `tm-body:transclusion` (or similar) is new in TW v5.3.4+ -- It seems TiddlyMap recognises the new "transclusions" and "backtransclusions", but does not know, what to do with it. 

I think I do have a fix. -- **But** I also needed to fix the gulp tasks because I did get an error message there. too. 

So do you accept PRs, once I'm sure it actually works?

**Comment by flibbles** [comment]
I'm *pretty sure* I'm able to merge PRs. Oh man. I can't believe that code is actually being used now. I added handling for transclusion edges to TiddlyMap almost 8 years ago, and I pushed a PR to Tiddlywiki for the core's side of it. I think I gave up on it ever being merged.

**Comment by pmario** [comment]
Are you able to build the stuff, with the current setup? --- I did get some problems. 

I'll post a PR that seems to work for me and you can have a closer look. From the PMs at Talk it seems it works for etardiff too.

**Comment by novo-redeunt** [comment]
Hello! Let me first express my appreciation for the work you are doing in general and TiddlyMap in particular. It has become an important part of my TiddlyWikis.

Is there any roadmap to release a new version of TiddlyMap with the RSOD fix? Or did I miss something?

**Comment by flibbles** [comment]
I was really hoping to get a reply from @pmario about the version change, and maybe about the sass stuff.

Also, I'm not able to replicate this bug. What do you do? You just have tiddlymap on a wiki, and you delete tiddlers that would be on the map? I'm not seeing that.

So yeah, sorry. This one fell of my plate. I'll try and look into it again today.

**Comment by pmario** [comment]
Here is how to replicate the problem

- Download empty.html from [tw-com GettingStarted](https://tiddlywiki.com/#GettingStarted)
- Download TiddlyMap from https://tiddlymap.org/ with the standard Save-Button
- Drag and drop import TiddlyMap into empty.html
- save and reload
- Create a new standard tiddler with + 
- Save tiddler
- Delete the tiddler from the More tab -> RSOD after "are you sure" dialogue
- Edit Tiddler -> Delete Button -> RSOD after dialogue

**Comment by novo-redeunt** [comment]
> Here is how to replicate the problem
> 
> * Download empty.html from [tw-com GettingStarted](https://tiddlywiki.com/#GettingStarted)
> * Download TiddlyMap from https://tiddlymap.org/ with the standard Save-Button
> * Drag and drop import TiddlyMap into empty.html
> * save and reload
> * Create a new standard tiddler with +
> * Save tiddler
> * Delete the tiddler from the Tiddler More tab -> RSOD after "are you sure" dialogue
> * Edit Tiddler -> Delete Button -> RSOD after dialogue
> 
> It does delete the tiddler. The RSOD comes from the function I linked to in the OP

Confirmation from my side.

**Comment by flibbles** [comment]
So the problem was that the `tw-body:transclude` edge type wasn't fully implemented. What happened is:

1. Felix and I added some of the framework for a transclude edge type.
2. [We introduce a getTiddlerTranscludes PR to Tiddlywiki](https://github.com/Jermolene/TiddlyWiki5/pull/2204) which is required for the edge type to work.
3. *8 years go by.*
4. the getTiddlerTranscludes method gets added independently by someone else in an unrelated discussion thread.
5. I have long since forgotten that there was a second part to the transclude edge type that I needed to implement.

I have completed the implementation. I have chosen `darkgreen` as the color. Tiddlywiki projects that create new views will have transclude edges disabled just as it has link edges disabled, but migrating projects with pre-existing views may need to add `-[[tw-body:transclude]]` to their  Edge-type filter.

The latest release shouldn't have the crash.
