### ISSUE TITLE
Confusing terminology in Tiddler dialog

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#49]
Add this node: talks about a graph editor -- should that be a map editor? Can we assume that the user is happy using "node" interchangeably with "tiddler"?

Link this node: uses a different meaning for link which elsewhere is edge, i.e. Add edges for this node

Delete connections: Delete edges

Small things but potentially confusing to the uninitiated. 

Unrelated: add a tooltip for the icon.

**Comment by felixhayashi** [comment]
Hi @Peter-Miller,

thanks for creating the issue. really good points. I always wanted to make my mind up how to call certain aspects/components/mechanisms of tiddlymap. The next days I will throw in some more points where I couldn't decide how to call them... Maybe we can discuss them.

**Comment by tobibeer** [comment]
I think it's good and important to not entirely drop graph-related notations. Not sure how both lingos can be merged without being prosaic.

**Comment by felixhayashi** [comment]
> I think it's good and important to not entirely drop graph-related notations. Not sure how both lingos can be merged without being prosaic.

Yes, I think so too. For example I used the word node to remind people that the tiddler is a node in a graph context. However, I think it is often better to use the word tiddler when not talking about a graph.

> Link this node: uses a different meaning for link which elsewhere is edge, i.e. Add edges for this node

The point is, some people are not familiar with the word edge and it might confuse them especially since the "quick connect dropdown" can be used without seeing a graph. But I get your point.

Maybe a compromise: "Create connection", complementary: "delete connection".  Alternatively: "create relation" and "delete relation"

> Delete connections: Delete edges

I would keep the this phrase then.

> Unrelated: add a tooltip for the icon.

Yes, I will do that.

> Add this node: talks about a graph editor -- should that be a map editor?

see my small dictionary below. However, I will call this "add tiddler to view".

> Can we assume that the user is happy using "node" interchangeably with "tiddler"?

When speaking in a graph context, yes. But I agree maybe it is better to use the word tiddler otherwise.

I will add this to the docs

**Editor**
Every graph canvas that also has a top-bar with editing options (displayed when adding the editor attribute to the tiddlymap widget element). Editors allow the creation of nodes via drag and dropping local tiddler links. "Creation of nodes" means that the tiddler id is automatically added to the node filter.

**Main Editor**
The editor that opens when clicking on the "map" tab in the sidebar

**Node**
Representation of a tiddler in a graph context.

**Edge**
A representation of a connection/relation between two tiddlers in a graph context.

**Quick connect dropdown**
The dropdown that is displayed when clicking on the tiddlymap button in the tiddler's toolbar.

-Felix

**Comment by tobibeer** [comment]
:+1:

**Comment by Peter-Miller** [comment]
I'm comfortable with the use of "edges" but my guess is that 80-90% of potential users will see it as weird. On the other hand software often uses familiar words in unfamiliar contexts, e.g. bug, so using it as a kind of TiddlyMap affectation is fine so long as there is a glossary entry (as there is now) . "Edge" also has the benefit of brevity. 

This is a bit marginal but I'm not sure that the use of "main editor" is appropriate given that most people see the story as the primary focus and the Map is quite possibly hidden. Maybe consider "sidebar editor"?

Incidentally, using Okay in buttons seems a little idiosyncratic; OK would be more usual?

**Comment by tobibeer** [comment]
"sirebar editor" ...or "sidebar map"

I also noticed the "okay" thing... seemed a wee unusual ^^

**Comment by felixhayashi** [comment]
ok I think you guys are right. Then I will call it "sidebar map editor" when speaking about it in the docs/examples. I use the word map as synonym for graph instances so "map editor" would fit any graph with an editor property and "sidebar" makes it clear that it is the editor in the sidebar ;)
