### ISSUE TITLE
Vocabulary used to describe TiddlyMap components/aspects

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#54]
This is an attempt to decide on some definite terms that are used in the TiddlyMap context. Related to issue #49.

**Map Editor** (also *graph editor*)
Every graph canvas that also has a top-bar with editing options (displayed when adding the editor attribute to the tiddlymap widget element). Editors allow the creation of nodes via drag and dropping local tiddler links. "Creation of nodes" means that the tiddler id is automatically added to the node filter.

**Sidebar Map Editor** (also *sidebar graph editor*, seldomly *main editor*)
The editor that opens when clicking on the "map" tab in the sidebar

**Editor mode vs. display mode**
When a tiddlymap widget has the *editor* attribute set, it runs in *editor mode*, meaning a topbar is displayed that gives the user the chance to actively manipulate the graph. Without the editor attribute, the widget runs in *display mode*, which means that the graph cannot be manipulated or changed in any way.

**Node**
Representation of a tiddler in a graph context.

**Edge**
A representation of a connection/relation between two tiddlers in a graph context.

**Quick connect dropdown**
The dropdown that is displayed when clicking on the tiddlymap button in the tiddler's toolbar.

**Map**
Map is a synonym for "graph".

**View**
A view defines which nodes and edges are displayed in a graph. It can be thought of as a filter or a preselect.

**Comment by tobibeer** [comment]
all that sounds well put to me

**Comment by christophvarga** [comment]
sounds clear to me.

**Comment by andtheWings** [comment]
So, I don't actually like the name TiddlyWiki, but I think it's instructive in explaining my criteria for a good name:

- Strong Semantics
- Memorable
- Aesthetically Sound

"TiddlyWiki" has deceptive semantics. The first part "Tiddly" is fine as it references a small fish as an analogy to a small unit of information. I do not like the use of "Wiki" because TiddlyWiki is not collaborative in the same way that Wikipedia or Smallest Federated Wiki are.

"TiddlyWiki" is very memorable. I think Jeremy specifically chose it as a name because it's silly and sticks in the brain so that's fine but...

It's not aesthetically sound...for me anyway. I know this is really qualitative, but when "Tiddly" comes out of my mouth it feels sort of squishy and unpleasant...or maybe even fishy. I love TiddlyWiki but I actually avoid using it's actual name when describing it to people because the name feels unpleasant. 

Ok so all this is meant to illustrate how I evaluate names. I think the terms you've listed above are very semantically sound but not particularly memorable or pleasing. I would challenge you to dream up something more creative for the initial release. I'll give it some thought too. You don't want the names so nonsensical that they're stripped of actual meaning, but you also want users to intuitively enjoy interacting with the plug-in, and part of that is names that stick out and are fun to say/use.

**Comment by Peter-Miller** [comment]
I tend to refer to the (very minor) applications I have written for student use as "Personal Wikis" that are based on TiddlyWiki and the various plugins, etc. This has some traction on Wikipedia at least http://en.wikipedia.org/wiki/Personal_wiki . 

I'm not going to proffer alternative names unless Felix wants them -- the problem is that many of the obvious ones are already "taken".

**Comment by andtheWings** [comment]
Both good points @Peter-Miller. 

And I wouldn't expect Felix to spend a lot of time on this since he's already doing all this other work and I'm the one who wants more exciting names. 

@felixhayashi, let me know if you'd be open to some alternative names if I find some dedicated time to brainstorm some.

**Comment by felixhayashi** [comment]
> Ok so all this is meant to illustrate how I evaluate names.

Great criterias! Thanks.

> I think the terms you've listed above are very semantically sound but not particularly memorable or pleasing.

As for "technical terms" like node, edge, view, editor, map I will keep the vocab because the chosen words are short, occur everywhere in my code and also for the reasons below:

* node and edge are used by the vis.js community
* map is the plugin name which I won't change anymore ;) It was already hard to find a suitable name as you remember (#18)
* view is loaded with meaning that suits me very well since I can quickly communicate its meaning to people from the db-resort (highly similar to SQL views) and normal people (view is similar to perspective; point of view). Btw, I recently tried to [graphically convey](http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Graph%20views) the meaning of views. 

> I'll give it some thought too. You don't want the names so nonsensical that they're stripped of actual meaning, but you also want users to intuitively enjoy interacting with the plug-in, and part of that is names that stick out and are fun to say/use. 

That sounds really nice, thanks.

> [...] I would challenge you to dream up something more creative for the initial release. 
> [...] @felixhayashi, let me know if you'd be open to some alternative names if I find some dedicated time to brainstorm some. 
> [...] I'm not going to proffer alternative names unless Felix wants them -- the problem is that many of the obvious ones are already "taken". 

Thanks, guys, I really appreciate if I get advice/feedback on the terms I plan to introduce or the ones I feel uncomfortable with. My understanding is the following:

* 98% of the public terms (that usually refer to minor components) need to have a high semantic to help a user with orientation. If a term exists that is suitable and highly understood, I prefer it.
* 2% of public terms represent the product and contribute to its identity. E.g. "TiddlyWiki", "Tiddler", "Story river", "TiddlyFox". They need to be like you, @andtheWings, described them memorable,
aesthetically sound, containing an analogy...

Maybe we can do it like this, I will introduce a github label "terminology" and post most words I plan to introduce (or I am uncomfortable with) tagged separately with this label. If you guys have the time, I would certainly appreciate your thoughts on these terms. If you dislike an existing expression, just create an issue, I will label it accordingly.

Providing that you are not upset if I should eventually decide against a proposal from your side (sometimes its taste against taste :), please do not hesitate to tell me your opinion!

-Felix

**Comment by andtheWings** [comment]
Sounds good!
