### ISSUE TITLE
reference a node name to another node name?

### ISSUE THREAD

**Issue by christophvarga** [felixhayashi/TW5-TiddlyMap#56]
can a node name (tiddler title) be referenced to another tiddlers name? so that if you change that one name all of the instances will change their name also?

e.g. when you write a film script and your actors name will appear in every second tiddler, and now the actors name should be changed. or when you document/design the structure of an GUI and all the terminology is not clarified, so that you have to change it afterwards

**Comment by felixhayashi** [comment]
Hi @christophvarga,

The problem is, in tiddlywiki the title is the id and changing a title will break all references to the title. So it is per design not possible to "bind" a title to another tiddler's title.

Still what I could do is to change the implementation of tiddlymap to allow wikitext in the *caption-field*. Then you could use a transclude to reference a different tiddler's fields and have it displayed as node title. Or you could use the list widget like discussed here: http://webapps.stackexchange.com/a/61219.

**Comment by tobibeer** [comment]
Actually, you could (allow to) set a **tmap-id** field that contains a unique id used with TiddlyMap, which will persist through title changes. One question is when that would be set and for what types of views / through what user-action. I sure would not want to touch shadow tiddlers matching a certain filter that way.

**Comment by felixhayashi** [comment]
Hi @tobibeer,

> Actually, you could (allow to) set a tmap-id field that contains a unique id used with TiddlyMap, which will persist through title changes.

Sorry, I expressed myself wrong. I already assign ids to tiddlers. Otherwise I could not track name changes (as we discussed in https://github.com/felixhayashi/TW5-TiddlyMap/issues/17#issuecomment-68193411). However, I think it is not the job of tiddlymap to bind/link tiddler titles to other tiddler titles. Instead the exsisting mechanisms of tiddlywiki should be used (e.g. using the list widget with a filter like posted here http://webapps.stackexchange.com/a/61219).

> I sure would not want to touch shadow tiddlers matching a certain filter that way.

Correct. I am not even touching system tiddlers (see #17). But I think of loosening this restriction so graphs may also contain system tiddlers (have to think about it again).

-Felix

**Comment by tobibeer** [comment]
> I am not even touching system tiddlers (see #17). But I think of loosening this restriction so graphs may also contain system tiddlers (have to think about it again)

I think that is an ok thing to do. But then how will TiddlyMap attributes or any other really survive something like the $:/core being upgraded?

**Comment by felixhayashi** [comment]
Because of stuff like this, I am unsure whether to allow this or not...

**Comment by tobibeer** [comment]
I guess that's an issue for the core to resolve and would require for either an option to "preserve custom properties" or some quite possibly over-engineered "related properties".

**Comment by felixhayashi** [comment]
"preserve custom properties" this sounds interesting. I mean it would allow to make update decisions on a field level possible and not every option would need to be outsourced as single tiddler as it is often done at the moment. But I am sure there are many drawbacks as well that I am not aware of at the moment ;) Anyway I will stick with non system tiddlers for now to avoid conflicts.

**Comment by felixhayashi** [comment]
see #57
