### ISSUE TITLE
All modals should be configuration tiddlers and displayed in the story view.

### ISSUE THREAD

**Issue by pmario** [felixhayashi/TW5-TiddlyMap#81]
IMO All the modals should be configuration tiddlers and displayed in the story view or in the tiddler info area. 

The modal views don't use the available space, so they contain lists with scrollbars.
For me they are extremely distracting. 

eg: 
global configuration could be part of the TW ControlPanel. 
manage edge types could be similar to the TW tag manager

**Comment by felixhayashi** [comment]
Hi @pmario 

> IMO All the modals should be configuration tiddlers and displayed in the story view or in the tiddler info area.

I carefully planned the interaction mechanism, so please let me give you the reasons, why I favour modals over tiddlers and why I cannot / will not change it. TiddlyMap is pretty complex and requires the user to make many decisions (~20 dialogs currently exist). Therefore, the modal mechanism is extremely critical for TiddlyMap and therefore highly advanced and automated.

---

#### Dialogs should not be configurable in any way

If a dialog (e.g. "Please state a node name" or "really remove node?" or "confirm delete view"...) is displayed as tiddler, you also see the tiddler toolbar. Confusing and dangerous (!) because the user may manipulate the underlying dialog or mess with the fields or accidentally click "close" (preventing the callback from being triggered) or "clone" or any other button in the toolbar.

#### Many actions require an answer and need to block the screen

How should I achieve this with a tiddler? Also I cannot intervene if the user presses the tiddler's close button and cannot prevent the user to simply continue what he/she is doing, even though I do not have a result yet.

#### Modals scroll / do not have space

Modals grow with the screen in size, so they potentially give me more space than a tiddler in the river which does not grow. The only reason they scroll vertically because I set the css so (please see https://github.com/felixhayashi/TW5-TiddlyMap/issues/51#issuecomment-74860245 and https://github.com/felixhayashi/TW5-TiddlyMap/issues/53).

#### Temporary dialogs should not interact with content in the river

Displaying a dialog in the river means to mix process decisions / interaction workflow with actual data/content.

#### Hiding dialogs / notifications

Dialogs that only inform about state may be hidden. E.g. create a new tiddler and press the clone button. You'll see an option "hide this dialog in the future". This technique is used on all pure "ok" dialogs.

Notififcations may be disabled in the tiddlymap configuration.

#### Inconsistency confuses

It is not good design to have some (configuration) dialogs show up in the river as normal tiddlers, some in the TW config and some as modals. So I chose modals as way to communicate with the user.

---

So while I highly value your opinion, please understand that I had to make a decision here.

-Felix
