### ISSUE TITLE
Editor bar dropdown to only show incoming or outgoing edges or both

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#90]
It would also be nice to turn inbound or outbound links to and from focus on or off:
```
[X]=>        [X]<= 
```
I am guessing I can already do this via styling somehow, but it seems useful enough to build in.  Making inbound and outbound from focus different colors by default would also be a boon to clarity I think.

**Comment by felixhayashi** [comment]
Hi @rcrath 

yes, it can already be done. See

* http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Tweaking%20the%20Graph

and add `edges.inheritColor = "from"`

I am very restrictive, what to add as option in the configuration menu because I do not want to bloat it now.

**Comment by rcrath** [comment]
thanks, will try it.

**Comment by rcrath** [comment]
I created the user tiddler at the noted path, and typed it json, added the text but saw no changes in the graph.  Do I then have to style things somewhere to pick up the "from" property?  Only slightly familiar with json (i.e. I know it is a nested data storage format) so sorry if this is obvious.

**Comment by felixhayashi** [comment]
Sorry, I just realized the description I gave in the docs and above is really bad (partly also wrong). When using JSON you do not use `=` but `:` and also need to add quotation marks everywhere so **not** `edges.inheritColor = "from"` **but** `"edges.inheritColor": "from"` and add curly brackets:

    {
      "edges.inheritColor": "from"
    }

alternatively, use the tiddlywiki data format and just add the following line to the tiddler's body:

    edges.inheritColor: from

> Do I then have to style things somewhere to pick up the "from" property?

Nope

**Comment by felixhayashi** [comment]
Hmm, seems like it doesn't work at the moment. I'll need to spot the problem here first...

**Comment by rcrath** [comment]
ok thanks.  I tried again and got no difference

**Comment by felixhayashi** [comment]
I only now understood what you asked for @rcrath :D You wanted to toggle only incoming or outgoing edges, somehow I thought you were only talking about the coloring. I think this is definitely worth implementing and would be a good idea to add a dedicated button in the editor menu.

I think it is fine if the button toggles globally? Or are there situations where a user wants to toggle per view?

-Felix

**Comment by felixhayashi** [comment]
Ok, I have almost finished with this one. It was a bit difficult because I needed to take into account that an edge may be styled to show different arrow heads. If an edge is styled having "from" and "to" arrow heads or no arrow heads at all then it is considered as bi-directional by the system when calculating the neighbourhood (see screenshots: the relationship between "getting started" and "Edge types").

I'll need to do more testing before a release though.

-Felix

![2015-11-23 01 59 20](https://cloud.githubusercontent.com/assets/4307137/11328218/52b64f8a-9186-11e5-87ea-4bf318474ca8.png)

![2015-11-23 01 59 59](https://cloud.githubusercontent.com/assets/4307137/11328221/5aa553d0-9186-11e5-8e0d-c927051c8b2d.png)


![2015-11-23 01 59 36](https://cloud.githubusercontent.com/assets/4307137/11328219/56e2ad24-9186-11e5-96c6-5de3e79deb98.png)

**Comment by joshuafontany** [comment]
Nice feature! :D

**Comment by rcrath** [comment]
@felixhayashi THank you, will watch for it!

**Comment by tobibeer** [comment]
@felixhayashi, very much improves graph readability, thanks a lot

**Comment by felixhayashi** [comment]
thanks guys
