### ISSUE TITLE
turn off "link to" edge label by default?

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#92]
THe default edge label in live view says "link to" but does not contain any information concerning the direction of the link.  The direction information is actually conveyed by the arrows, and the edge itself indicates the link, so it would seem to me to make sense to leave the "link to" label off by default to clean up the graph by removing redundant information.

**Comment by felixhayashi** [comment]
True :) but I wanted to highlight here that the connection that is drawn is auto-generated from a link, otherwise the user might say "where does this edge come from? I didn't draw it...". So I want to leave "links to" as default. It is very easy to turn the edge label off systemwide by using the edge type manager (by clicking on the edge) and deselecting "show label".

**Comment by rcrath** [comment]
yep, that was easy enough!
