### ISSUE TITLE
suggestion: tags version of live view

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#93]
I would find it useful to have a live view map of links via tags, so that for Tiddler 1 with tags A, B, and C, 1 would link to A, B, and C as nodes that in turn have edges leading to all the tiddlers tagged with each respective tag.

**Comment by felixhayashi** [comment]
Still to come ;)

**Comment by felixhayashi** [comment]
see #14

**Comment by andtheWings** [comment]
I have some views where a node is named the same thing as the tag used in a filter. Since updating to latest version, there dark green edges that automatically connect all other nodes to the node with the same name as the filter-tag. Is this feature what's causing this to happen? Is there a way to toggle it on and off?

**Comment by felixhayashi** [comment]
Hi @andtheWings 

> Is there a way to toggle it on and off?

Yes, certainly.

Sorry, I haven't updated the docs but basically it goes like this.

All edge-types are stored below the path `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/`. For example the link type is `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tmap:link`. So if you want to disable an edge-type, you have to do the following:

Just go to the view you want to change and in the menu click on "Edit filters" and change it into the following:

    [prefix[$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes]]
    -[suffix[tmap:tag]]

This will select all types except the ones with a suffix `tmap:tag`.

-Felix

**Comment by andtheWings** [comment]
Thanks!
